import Link from "next/link";
import { notFound } from "next/navigation";
import { changeQuoteStatus, confirmQuote, updateQuote } from "@/app/actions/quotes";
import { prisma } from "@/server/db/prisma";
import { requireManagement } from "@/server/auth/authorization";
import { formatMoney } from "@/lib/money/format";
import { suggestSetupTime } from "@/lib/dates/times";
import { ProposalActions } from "@/components/quotes/proposal-actions";
import { buildProposalWhatsappMessage } from "@/lib/quotes/proposal";

export default async function QuoteDetail({params}:{params:Promise<{id:string}>}){
  await requireManagement(); const {id}=await params;
  const [q,clients,types]=await Promise.all([
    prisma.quote.findUnique({where:{id},include:{client:true,eventType:true,event:true,versions:{include:{items:true,createdBy:true},orderBy:{versionNumber:"desc"}}}}),
    prisma.client.findMany({where:{active:true},orderBy:{name:"asc"},select:{id:true,name:true}}),
    prisma.eventType.findMany({where:{active:true},orderBy:{name:"asc"},select:{id:true,name:true}})
  ]); if(!q)notFound();
  return <>
    <div className="topbar"><div><div className="eyebrow">{q.number}</div><h1>{q.client.name}</h1><div className="row" style={{marginTop:10}}><span className="badge badge-green">{q.status.replaceAll("_"," ")}</span><span className="muted">{q.eventType.name} · {q.eventDate.toLocaleDateString("es-AR",{timeZone:"UTC"})}</span></div></div><Link className="btn btn-primary" href={`/presupuestos/${id}/editar`}>+ Nueva versión</Link></div>
    <section className="card row space"><div><strong>{q.venue}</strong><div className="muted">{q.startTime}–{q.endTime} · {q.locality||q.address||"Sin dirección"}</div></div>{q.event?<Link className="btn btn-accent" href={`/eventos/${q.event.id}`}>Ver evento</Link>:<form action={async(formData)=>{"use server";await changeQuoteStatus(id,String(formData.get("status")) as never)}} className="row"><select aria-label="Estado" name="status" defaultValue={q.status}>{["CONSULTA","PRESUPUESTO_ENVIADO","EN_NEGOCIACION","ESPERANDO_SENA","CANCELADO"].map(s=><option key={s}>{s}</option>)}</select><button className="btn btn-secondary">Cambiar estado</button></form>}</section>
    <details className="card edit-quote"><summary>Editar datos del presupuesto</summary><form action={updateQuote.bind(null,id)} className="form edit-panel">{q.event&&<p className="notice">Este presupuesto ya generó un evento. Los cambios se guardan aquí, pero no actualizan el evento automáticamente.</p>}<div className="form-grid"><div className="field"><label>Cliente</label><select name="clientId" defaultValue={q.clientId} required>{clients.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></div><div className="field"><label>Tipo de evento</label><select name="eventTypeId" defaultValue={q.eventTypeId} required>{types.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></div><div className="field"><label>Fecha</label><input name="eventDate" type="date" defaultValue={q.eventDate.toISOString().slice(0,10)} required/></div><div className="field"><label>Invitados</label><input name="guestCount" type="number" min="1" defaultValue={q.guestCount||""}/></div><div className="field"><label>Inicio</label><input name="startTime" type="time" defaultValue={q.startTime} required/></div><div className="field"><label>Finalización</label><input name="endTime" type="time" defaultValue={q.endTime} required/></div><div className="field span-2"><label>Lugar</label><input name="venue" defaultValue={q.venue} required/></div><div className="field"><label>Dirección</label><input name="address" defaultValue={q.address||""}/></div><div className="field"><label>Localidad</label><input name="locality" defaultValue={q.locality||""}/></div><div className="field span-2"><label>Google Maps</label><input name="googleMapsUrl" type="url" defaultValue={q.googleMapsUrl||""}/></div><div className="field span-2"><label>Notas</label><textarea name="notes" defaultValue={q.notes||""}/></div></div><button className="btn btn-primary">Guardar datos</button></form></details>
    <div className="section-head"><h2>Historial de versiones</h2></div><div className="stack">{q.versions.map(v=>{const proposalMessage=buildProposalWhatsappMessage({clientName:q.client.name,eventType:q.eventType.name,eventDate:q.eventDate,startTime:q.startTime,endTime:q.endTime,venue:q.venue,locality:q.locality,guestCount:q.guestCount,total:String(v.totalFinal),depositPercentage:String(v.depositPercentage),depositAmount:String(v.depositAmount),currency:v.currency});return <article className="card" key={v.id}><div className="row space"><div><h2 style={{margin:0}}>Versión {v.versionNumber}</h2><div className="muted">{v.createdAt.toLocaleString("es-AR")} · {v.createdBy.name}</div></div><strong style={{fontSize:24}}>{formatMoney(String(v.totalFinal),v.currency)}</strong></div><div className="proposal-version-actions"><ProposalActions quoteId={id} proposalUrl={`/presupuestos/${id}/propuesta/${v.id}`} message={proposalMessage}/></div><div className="table-wrap" style={{marginTop:16}}><table className="table"><thead><tr><th>Concepto</th><th>Cant.</th><th>Lista</th><th>Descuento</th><th>Final</th></tr></thead><tbody>{v.items.map(i=><tr key={i.id}><td data-label="Concepto">{i.description}</td><td data-label="Cant.">{String(i.quantity)}</td><td data-label="Lista">{formatMoney(String(i.grossAmount),i.currency)}</td><td data-label="Descuento">{formatMoney(String(i.discountAmount),i.currency)}</td><td data-label="Final"><strong>{formatMoney(String(i.finalAmount),i.currency)}</strong></td></tr>)}</tbody></table></div><div className="totals" style={{marginTop:12}}><R label="Subtotal bruto" value={formatMoney(String(v.grossSubtotal),v.currency)}/><R label="Descuentos por ítem" value={`− ${formatMoney(String(v.itemDiscountTotal),v.currency)}`}/><R label="Descuento general" value={`− ${formatMoney(String(v.generalDiscountAmount),v.currency)}`}/><R label="Base imponible" value={formatMoney(String(v.taxableBase),v.currency)}/><R label={`IVA ${Number(v.taxRate)}%`} value={formatMoney(String(v.taxAmount),v.currency)}/><R label="Total" value={formatMoney(String(v.totalFinal),v.currency)} final/><R label={`Seña ${Number(v.depositPercentage)}%`} value={formatMoney(String(v.depositAmount),v.currency)}/></div>{!q.event&&<form action={async(formData)=>{"use server";await confirmQuote(id,v.id,String(formData.get("setupTime")))}} className="row" style={{marginTop:16,justifyContent:"flex-end"}}><div className="field"><label>Hora de armado sugerida</label><input name="setupTime" type="time" defaultValue={suggestSetupTime(q.startTime)}/></div><button className="btn btn-accent">Confirmar esta versión y crear evento</button></form>}</article>})}{!q.versions.length&&<div className="card empty">Este presupuesto todavía no tiene versiones. <Link href={`/presupuestos/${id}/editar`}>Armá la primera.</Link></div>}</div>
  </>
}
function R({label,value,final=false}:{label:string;value:string;final?:boolean}){return <div className={`total-row ${final?"total-final":""}`}><span>{label}</span><span>{value}</span></div>}
