import { randomUUID } from "node:crypto";
import Link from "next/link";
import { Currency,FinancialAccountType,TreasuryDirection } from "@prisma/client";
import { requireManagement } from "@/server/auth/authorization";
import { prisma } from "@/server/db/prisma";
import { treasurySummary } from "@/server/treasury/summary";
import { formatMoney } from "@/lib/money/format";
import { humanLabel } from "@/lib/ui/labels";
import { createAccountTransfer,createAdjustment,createFinancialAccount,createOpeningBalance,createOwnerMovement,updateFinancialSetting } from "@/app/actions/treasury";

export default async function TreasuryPage(){const actor=await requireManagement(),summary=await treasurySummary(),accounts=summary.accounts,staff=await prisma.staff.findMany({where:{active:true},orderBy:{name:"asc"}});return <>
 <div className="topbar"><div><div className="eyebrow">Caja y disponibilidad</div><h1>Tesorería</h1><p className="muted">Caja real, obligaciones y reservas. No equivale a rentabilidad.</p></div><div className="row"><Link className="btn btn-secondary" href="/tesoreria/movimientos">Movimientos</Link><Link className="btn btn-secondary" href="/tesoreria/flujo">Flujo de caja</Link></div></div>
 {Object.values(Currency).map(currency=>{const b=summary.buckets[currency];return <section key={currency}><div className="section-head"><h2>{currency}</h2></div><div className="grid grid-4 treasury-metrics"><Metric label="Saldo en cuentas" value={formatMoney(b.availableCash.toFixed(2),currency)}/><Metric label="Por cobrar" value={formatMoney(b.receivable.toFixed(2),currency)}/><Metric label="Por pagar" value={formatMoney(b.payable.toFixed(2),currency)}/><Metric label="IVA a reservar" value={formatMoney(b.taxReserve.toFixed(2),currency)}/><Metric label="Disponibilidad estimada" value={formatMoney(b.estimated.toFixed(2),currency)} accent/><Metric label="Reserva mínima" value={formatMoney(b.minimumReserve.toFixed(2),currency)}/><Metric label="Excedente sobre reserva" value={formatMoney(b.overReserve.toFixed(2),currency)}/><Metric label="Fondos en terceros" value={formatMoney(b.thirdParty.toFixed(2),currency)}/></div></section>})}
 <div className="row treasury-links"><Link className="card card-interactive" href="/tesoreria/por-cobrar"><strong>Por cobrar</strong><span>Clientes y eventos →</span></Link><Link className="card card-interactive" href="/tesoreria/por-pagar"><strong>Por pagar</strong><span>Personal y reintegros →</span></Link></div>
 <div className="section-head"><div><h2>Operaciones</h2><p className="muted section-copy">Movimientos manuales y ajustes excepcionales.</p></div></div><section className="grid grid-2 treasury-operations">
  <Panel title="Transferir entre cuentas"><form action={createAccountTransfer} className="form"><AccountSelect name="fromAccountId" label="Desde" accounts={accounts}/><AccountSelect name="toAccountId" label="Hacia" accounts={accounts}/><MoneyDate dateName="transferDate"/><input type="hidden" name="idempotencyKey" value={randomUUID()}/><div className="field"><label>Descripción</label><input name="description"/></div><button className="btn btn-primary">Transferir</button></form></Panel>
  {actor.role==="ADMIN"&&<Panel title="Saldo inicial"><form action={createOpeningBalance} className="form"><AccountSelect name="accountId" label="Cuenta" accounts={accounts}/><div className="field"><label>Importe</label><input name="amount" type="number" min="0.01" step="0.01" required/></div><div className="field"><label>Fecha de corte</label><input name="balanceDate" type="date" defaultValue={today()} required/></div><input type="hidden" name="idempotencyKey" value={randomUUID()}/><button className="btn btn-primary">Registrar saldo inicial</button></form></Panel>}
  {actor.role==="ADMIN"&&<Panel title="Ajuste auditado"><form action={createAdjustment} className="form"><AccountSelect name="accountId" label="Cuenta" accounts={accounts}/><select name="direction" aria-label="Dirección">{Object.values(TreasuryDirection).map(x=><option key={x} value={x}>{humanLabel(x)}</option>)}</select><MoneyDate dateName="transactionDate"/><input type="hidden" name="idempotencyKey" value={randomUUID()}/><div className="field"><label>Motivo</label><input name="reason" required/></div><button className="btn btn-primary">Registrar ajuste</button></form></Panel>}
  {actor.role==="ADMIN"&&<Panel title="Retiro o aporte"><form action={async(data)=>{"use server";await createOwnerMovement(String(data.get("kind")) as "WITHDRAWAL"|"CONTRIBUTION",data)}} className="form"><select name="kind" aria-label="Tipo"><option value="WITHDRAWAL">Retiro</option><option value="CONTRIBUTION">Aporte</option></select><AccountSelect name="accountId" label="Cuenta" accounts={accounts}/><MoneyDate dateName="movementDate"/><select name="staffId" aria-label="Persona"><option value="">Sin asignar</option>{staff.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><input type="hidden" name="idempotencyKey" value={randomUUID()}/><button className="btn btn-primary">Registrar</button></form></Panel>}
 </section>
 {actor.role==="ADMIN"&&<details className="settings-panel treasury-settings"><summary><span><strong>Configuración financiera</strong><small>Reservas, fecha de control y cuentas disponibles.</small></span><span>Administrar</span></summary><section className="grid grid-2 settings-content">{Object.values(Currency).map(currency=>{const setting=summary.buckets[currency];return <form action={updateFinancialSetting.bind(null,currency)} className="form" key={currency}><h3>{currency}</h3><div className="field"><label>Reserva mínima</label><input name="minimumCashReserve" type="number" min="0" step="0.01" defaultValue={setting.minimumReserve.toFixed(2)}/></div><div className="field"><label>Inicio de control financiero</label><input name="financialTrackingStartDate" type="date"/></div><button className="btn btn-secondary">Guardar configuración</button></form>})}<form action={createFinancialAccount} className="form"><h3>Nueva cuenta</h3><div className="field"><label>Nombre</label><input name="name" required/></div><select name="type" aria-label="Tipo de cuenta">{Object.values(FinancialAccountType).map(x=><option key={x} value={x}>{humanLabel(x)}</option>)}</select><select name="currency" aria-label="Moneda"><option>ARS</option><option>USD</option></select><label className="row"><input name="includeInAvailableCash" value="true" type="checkbox" defaultChecked/> Incluir en disponibilidad</label><button className="btn btn-secondary">Crear cuenta</button></form></section></details>}
 <p className="muted treasury-disclaimer">Disponibilidad estimada = saldo de cuentas Murray − obligaciones exigibles − reintegros pendientes − IVA cobrado a reservar. No contempla compromisos no registrados ni decisiones de inversión.</p>
 </>}
function Metric({label,value,accent=false}:{label:string;value:string;accent?:boolean}){return <div className={`card metric ${accent?"metric-result":""}`}><span>{label}</span><strong>{value}</strong></div>}
function Panel({title,children}:{title:string;children:React.ReactNode}){return <details className="operation-disclosure"><summary>{title}</summary><div>{children}</div></details>}
function AccountSelect({name,label,accounts}:{name:string;label:string;accounts:Array<{id:string;name:string;currency:Currency}>}){return <div className="field"><label>{label}</label><select name={name} required>{accounts.map(a=><option key={a.id} value={a.id}>{a.name} · {a.currency}</option>)}</select></div>}
function MoneyDate({dateName}:{dateName:string}){return <><div className="field"><label>Importe</label><input name="amount" type="number" min="0.01" step="0.01" required/></div><div className="field"><label>Fecha</label><input name={dateName} type="date" defaultValue={today()} required/></div></>}
function today(){return new Date().toISOString().slice(0,10)}
