import { EventStatus } from "@prisma/client";
import { updateImportedEvent } from "@/app/actions/excel-import";

type StaffOption={id:string;name:string};
type EventTypeOption={id:string;name:string};
type Legacy={saleArs:unknown;saleUsd:unknown;depositArs:unknown;depositUsd:unknown;costArs:unknown;costUsd:unknown;resultArs:unknown;resultUsd:unknown};
type ImportedEvent={id:string;eventTypeId:string;eventDate:Date;startTime:string;endTime:string;setupTime:string|null;venue:string;address:string|null;locality:string|null;managerStaffId:string|null;status:EventStatus;notes:string|null;client:{name:string};legacyFinancialData:Legacy|null};
const value=(input:unknown)=>input==null?"":String(input);
export function LegacyEventEditor({event,staff,eventTypes}:{event:ImportedEvent;staff:StaffOption[];eventTypes:EventTypeOption[]}){const legacy=event.legacyFinancialData;return <details className="card"><summary>Editar evento importado</summary><form action={updateImportedEvent} className="form edit-panel"><input type="hidden" name="eventId" value={event.id}/><div className="form-grid"><div className="field"><label>Tipo de evento</label><select name="eventTypeId" defaultValue={event.eventTypeId} required>{eventTypes.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></div><Field label="Cliente" name="clientName" defaultValue={event.client.name} required/><Field label="Fecha" name="eventDate" type="date" defaultValue={event.eventDate.toISOString().slice(0,10)} required/><Field label="Hora inicio" name="startTime" type="time" defaultValue={event.startTime} required/><Field label="Hora fin" name="endTime" type="time" defaultValue={event.endTime} required/><Field label="Hora de armado" name="setupTime" type="time" defaultValue={event.setupTime||""}/><Field label="Lugar" name="venue" defaultValue={event.venue} required/><Field label="Dirección" name="address" defaultValue={event.address||""}/><Field label="Localidad" name="locality" defaultValue={event.locality||""}/><div className="field"><label>Encargado</label><select name="managerStaffId" defaultValue={event.managerStaffId||""}><option value="">Sin definir</option>{staff.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></div><div className="field"><label>Estado</label><select name="status" defaultValue={event.status}>{Object.values(EventStatus).map(item=><option key={item}>{item}</option>)}</select></div><Money label="Venta Excel ARS" name="saleArs" defaultValue={value(legacy?.saleArs)}/><Money label="Venta Excel USD" name="saleUsd" defaultValue={value(legacy?.saleUsd)}/><Money label="Seña Excel ARS" name="depositArs" defaultValue={value(legacy?.depositArs)}/><Money label="Seña Excel USD" name="depositUsd" defaultValue={value(legacy?.depositUsd)}/><Money label="Costo Excel ARS" name="costArs" defaultValue={value(legacy?.costArs)}/><Money label="Costo Excel USD" name="costUsd" defaultValue={value(legacy?.costUsd)}/><Money label="Resultado Excel ARS" name="resultArs" defaultValue={value(legacy?.resultArs)}/><Money label="Resultado Excel USD" name="resultUsd" defaultValue={value(legacy?.resultUsd)}/><div className="field span-2"><label>Observaciones</label><textarea name="notes" defaultValue={event.notes||""}/></div></div><div className="alert">Editar estos importes actualiza solamente el snapshot histórico. No genera movimientos de caja.</div><button className="btn btn-primary">Guardar cambios</button></form></details>}
function Field({label,name,defaultValue,type="text",required=false}:{label:string;name:string;defaultValue:string;type?:string;required?:boolean}){return <div className="field"><label>{label}</label><input name={name} type={type} defaultValue={defaultValue} required={required}/></div>}
function Money({label,name,defaultValue}:{label:string;name:string;defaultValue:string}){return <div className="field"><label>{label}</label><input name={name} type="number" step="0.01" defaultValue={defaultValue}/></div>}
