"use client";
import { useState } from "react";
import { createQuote } from "@/app/actions/quotes";

type Option={id:string;name:string};
export function NewQuoteForm({clients,eventTypes}:{clients:Option[];eventTypes:Option[]}){
  const [mode,setMode]=useState<"EXISTING"|"NEW">(clients.length?"EXISTING":"NEW");
  return <form action={createQuote} className="card form">
    <fieldset className="choice-group"><legend>Cliente</legend><label><input type="radio" name="clientMode" value="EXISTING" checked={mode==="EXISTING"} disabled={!clients.length} onChange={()=>setMode("EXISTING")}/> Existente</label><label><input type="radio" name="clientMode" value="NEW" checked={mode==="NEW"} onChange={()=>setMode("NEW")}/> Nuevo cliente</label></fieldset>
    {mode==="EXISTING"?<div className="field"><label htmlFor="clientId">Cliente *</label><select id="clientId" name="clientId" required>{clients.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></div>:<section className="subform" aria-label="Datos del nuevo cliente"><h2>Nuevo cliente</h2><div className="form-grid"><div className="field"><label htmlFor="clientName">Nombre / razón social *</label><input id="clientName" name="clientName" required/></div><div className="field"><label htmlFor="clientType">Tipo *</label><select id="clientType" name="clientType"><option value="PARTICULAR">Particular</option><option value="EMPRESA">Empresa</option></select></div><div className="field"><label htmlFor="clientPhone">Teléfono</label><input id="clientPhone" name="clientPhone" inputMode="tel"/></div><div className="field"><label htmlFor="clientEmail">Email</label><input id="clientEmail" name="clientEmail" type="email"/></div><div className="field"><label htmlFor="contactName">Contacto principal</label><input id="contactName" name="contactName"/></div><div className="field"><label htmlFor="contactPhone">Teléfono del contacto</label><input id="contactPhone" name="contactPhone" inputMode="tel"/></div></div></section>}
    <div className="section-divider"><span>Datos del evento</span></div>
    <div className="form-grid"><div className="field"><label htmlFor="eventTypeId">Tipo de evento *</label><select id="eventTypeId" name="eventTypeId" required>{eventTypes.map(t=><option value={t.id} key={t.id}>{t.name}</option>)}</select></div><div className="field"><label htmlFor="eventDate">Fecha *</label><input id="eventDate" name="eventDate" type="date" required/></div><div className="field"><label htmlFor="guestCount">Invitados</label><input id="guestCount" name="guestCount" type="number" min="1"/></div><div className="field"><label htmlFor="venue">Lugar *</label><input id="venue" name="venue" required/></div><div className="field"><label htmlFor="startTime">Inicio *</label><input id="startTime" name="startTime" type="time" required/></div><div className="field"><label htmlFor="endTime">Finalización *</label><input id="endTime" name="endTime" type="time" required/></div><div className="field"><label htmlFor="address">Dirección</label><input id="address" name="address"/></div><div className="field"><label htmlFor="locality">Localidad</label><input id="locality" name="locality"/></div><div className="field span-2"><label htmlFor="googleMapsUrl">Google Maps</label><input id="googleMapsUrl" name="googleMapsUrl" type="url"/></div></div><button className="btn btn-primary">Crear y agregar servicios</button>
  </form>
}
