"use client";
import { useMemo, useRef, useState, useTransition } from "react";
import { Plus, Trash2, X } from "lucide-react";
import { useRouter } from "next/navigation";
import { saveQuoteVersion } from "@/app/actions/quotes";
import { calculateQuote } from "@/lib/money/quote-calculator";
import { formatMoney } from "@/lib/money/format";

type Currency="ARS"|"USD"; type DType="NONE"|"PERCENTAGE"|"FIXED";
type Item={key:string;type:"SERVICE"|"ADD_ON"|"CUSTOM";serviceId?:string;addOnId?:string;description:string;quantity:number;listUnitPrice:number;currency:Currency;discount:{type:DType;value:number}};
type Catalog={id:string;name:string;listPrice:number;currency:Currency};

export function QuoteEditor({quoteId,services,addOns,basePackage,initial}:{quoteId:string;services:Catalog[];addOns:Catalog[];basePackage?:Catalog;initial?:{currency:Currency;items:Item[];generalDiscount:{type:DType;value:number};taxRate:number;depositPercentage:number}}){
 const router=useRouter(),currencyDialog=useRef<HTMLDialogElement>(null);const [pending,start]=useTransition();
 const initialPackage:Item|undefined=basePackage?{key:"base-package",type:"SERVICE",serviceId:basePackage.id,description:"Producción para fiestas de 50",quantity:1,listUnitPrice:basePackage.listPrice,currency:basePackage.currency,discount:{type:"NONE",value:0}}:undefined;
 const [currency,setCurrency]=useState<Currency>(initial?.currency||basePackage?.currency||"ARS"),[nextCurrency,setNextCurrency]=useState<Currency|null>(null),[items,setItems]=useState<Item[]>(initial?.items||[]);
 const [generalType,setGeneralType]=useState<DType>(initial?.generalDiscount.type||"NONE"),[generalValue,setGeneralValue]=useState(initial?.generalDiscount.value||0),[taxRate,setTaxRate]=useState(initial?.taxRate??0),[deposit,setDeposit]=useState(initial?.depositPercentage??50),[error,setError]=useState("");
 const result=useMemo(()=>{try{return calculateQuote({items,generalDiscount:{type:generalType,value:generalValue},taxRate,depositPercentage:deposit})}catch{return null}},[items,generalType,generalValue,taxRate,deposit]);
 const availableServices=services.filter(x=>x.currency===currency),availableAddOns=addOns.filter(x=>x.currency===currency);
 function add(type:Item["type"]){const source=type==="SERVICE"?availableServices[0]:type==="ADD_ON"?availableAddOns[0]:undefined;if(type!=="CUSTOM"&&!source){setError(`No hay ${type==="SERVICE"?"servicios":"adicionales"} en ${currency}`);return}setItems(x=>[...x,{key:crypto.randomUUID(),type,serviceId:type==="SERVICE"?source?.id:undefined,addOnId:type==="ADD_ON"?source?.id:undefined,description:source?.name||"Concepto personalizado",quantity:1,listUnitPrice:source?.listPrice||0,currency,discount:{type:"NONE",value:0}}])}
 function patch(key:string,data:Partial<Item>){setItems(x=>x.map(i=>i.key===key?{...i,...data}:i))}
 function choose(key:string,type:Item["type"],id:string){const source=(type==="SERVICE"?services:addOns).find(x=>x.id===id);if(source)patch(key,{description:source.name,listUnitPrice:source.listPrice,currency:source.currency,serviceId:type==="SERVICE"?id:undefined,addOnId:type==="ADD_ON"?id:undefined})}
 function addBasePackage(){if(!initialPackage)return;if(items.some(item=>item.serviceId===initialPackage.serviceId)){setError("La producción para fiestas de 50 ya está incluida.");return}setItems(items=>[...items,{...initialPackage,key:crypto.randomUUID()}])}
 function requestCurrency(value:Currency){if(!items.length){setCurrency(value);return}setNextCurrency(value);currencyDialog.current?.showModal()}
 function confirmCurrency(){if(nextCurrency){setCurrency(nextCurrency);setItems([])}setNextCurrency(null);currencyDialog.current?.close()}
 function submit(){setError("");if(!result){setError("Revisá cantidades, precios y descuentos. Ningún descuento puede superar el importe disponible.");return}start(async()=>{try{await saveQuoteVersion(quoteId,JSON.stringify({currency,items:items.map(i=>({type:i.type,serviceId:i.serviceId,addOnId:i.addOnId,description:i.description,quantity:i.quantity,listUnitPrice:i.listUnitPrice,currency:i.currency,discount:i.discount})),generalDiscount:{type:generalType,value:generalValue},taxRate,taxName:taxRate>0?"IVA":"",depositPercentage:deposit}));router.push(`/presupuestos/${quoteId}`)}catch(e){setError(e instanceof Error?e.message:"No se pudo guardar")}})}
 return <div className="quote-workspace">
  <section className="card quote-currency"><div className="row space"><div><div className="eyebrow">Moneda de la versión</div><h2 style={{margin:"5px 0"}}>{currency}</h2></div><select aria-label="Moneda" value={currency} onChange={e=>requestCurrency(e.target.value as Currency)}><option>ARS</option><option>USD</option></select></div></section>
  <div className="section-head quote-heading"><div><h2>Servicios y adicionales</h2>{!initial&&basePackage&&<p className="muted quote-package-note">Arrancá con el paquete de “Producción para fiestas de 50” o armá una propuesta a medida.</p>}</div><div className="row">{!initial&&basePackage&&<button className="btn btn-primary" onClick={addBasePackage}><Plus size={17}/>Fiesta de 50</button>}<button className="btn btn-secondary" onClick={()=>add("SERVICE")}><Plus size={17}/>Servicio</button><button className="btn btn-secondary" onClick={()=>add("ADD_ON")}><Plus size={17}/>Adicional</button><button className="btn btn-secondary" onClick={()=>add("CUSTOM")}><Plus size={17}/>Otro</button></div></div>
  <div className="quote-items stack">{items.map((item,index)=><div className="item-card" key={item.key}><div className="row space"><strong>{index+1}. {item.type==="SERVICE"?"Servicio":item.type==="ADD_ON"?"Adicional":"Personalizado"}</strong><button className="btn btn-danger icon-btn" aria-label={`Quitar ${item.description}`} onClick={()=>setItems(x=>x.filter(i=>i.key!==item.key))}><Trash2 size={17}/></button></div><div className="form-grid" style={{marginTop:12}}>{item.type!=="CUSTOM"?<div className="field span-2"><label>Concepto</label><select value={item.serviceId||item.addOnId} onChange={e=>choose(item.key,item.type,e.target.value)}>{(item.type==="SERVICE"?availableServices:availableAddOns).map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select></div>:<div className="field span-2"><label>Descripción</label><input value={item.description} onChange={e=>patch(item.key,{description:e.target.value})}/></div>}<div className="field"><label>Cantidad</label><input type="number" min="0.01" step="0.01" value={item.quantity} onChange={e=>patch(item.key,{quantity:Number(e.target.value)})}/></div><div className="field"><label>Precio de lista unitario</label><input type="number" min="0" step="0.01" value={item.listUnitPrice} onChange={e=>patch(item.key,{listUnitPrice:Number(e.target.value)})}/></div><div className="field"><label>Descuento del ítem</label><select value={item.discount.type} onChange={e=>patch(item.key,{discount:{...item.discount,type:e.target.value as DType}})}><option value="NONE">Sin descuento</option><option value="PERCENTAGE">Porcentaje</option><option value="FIXED">Importe fijo</option></select></div><div className="field"><label>Valor del descuento</label><input type="number" min="0" step="0.01" disabled={item.discount.type==="NONE"} value={item.discount.value} onChange={e=>patch(item.key,{discount:{...item.discount,value:Number(e.target.value)}})}/></div></div></div>)}{!items.length&&<div className="card empty"><strong>Todavía no hay conceptos</strong>Agregá al menos un servicio o adicional.</div>}</div>
  <section className="card form quote-summary"><div><div className="eyebrow">Resumen de la versión</div><h2 style={{margin:"6px 0 0"}}>Totales</h2></div><div className="form-grid"><div className="field"><label>Descuento general</label><select value={generalType} onChange={e=>setGeneralType(e.target.value as DType)}><option value="NONE">Sin descuento</option><option value="PERCENTAGE">Porcentaje</option><option value="FIXED">Importe fijo</option></select></div><div className="field"><label>Valor</label><input type="number" min="0" step="0.01" disabled={generalType==="NONE"} value={generalValue} onChange={e=>setGeneralValue(Number(e.target.value))}/></div><div className="field"><label>IVA</label><select value={taxRate} onChange={e=>setTaxRate(Number(e.target.value))}><option value="0">No corresponde</option><option value="21">IVA 21%</option></select></div><div className="field"><label>Seña (%)</label><input type="number" min="0" max="100" step="0.01" value={deposit} onChange={e=>setDeposit(Number(e.target.value))}/></div></div>{result&&<div className="totals"><Line label="Subtotal bruto" value={result.grossSubtotal}/><Line label="Descuentos por ítem" value={result.itemDiscountTotal} negative/><Line label="Descuento general" value={result.generalDiscountAmount} negative/><Line label="Base imponible" value={result.taxableBase}/><Line label={`IVA ${taxRate}%`} value={result.taxAmount}/><div className="total-row total-final"><span>Total final</span><span>{formatMoney(result.totalFinal.toFixed(2),currency)}</span></div><Line label={`Seña ${deposit}%`} value={result.depositAmount}/><Line label="Saldo" value={result.balance}/></div>}{error&&<div className="error" role="alert">{error}</div>}<button className="btn btn-primary" onClick={submit} disabled={pending||!items.length}>{pending?"Guardando versión…":"Guardar nueva versión"}</button></section>
  <dialog ref={currencyDialog} className="dialog"><div className="dialog-panel"><header><div><div className="eyebrow">Confirmación</div><h2>Cambiar moneda</h2></div><button className="btn btn-ghost dialog-close" onClick={()=>currencyDialog.current?.close()} aria-label="Cerrar"><X size={20}/></button></header><p className="muted">Al cambiar la moneda se quitarán los ítems actuales de esta versión.</p><div className="dialog-actions"><button className="btn btn-secondary" onClick={()=>currencyDialog.current?.close()}>Cancelar</button><button className="btn btn-danger" onClick={confirmCurrency}>Cambiar y quitar ítems</button></div></div></dialog>
 </div>;
 function Line({label,value,negative=false}:{label:string;value:{toFixed:(n:number)=>string};negative?:boolean}){return <div className="total-row"><span>{label}</span><span>{negative?"− ":""}{formatMoney(value.toFixed(2),currency)}</span></div>}
}
