import { notFound } from "next/navigation";
import Link from "next/link";
import { PaymentMethod,PaymentType,StaffRole } from "@prisma/client";
import { prisma } from "@/server/db/prisma";
import { requireManagement } from "@/server/auth/authorization";
import { formatMoney } from "@/lib/money/format";
import { calculateStaffFinance } from "@/lib/staff/finance";
import { createStaffPayment,voidStaffPayment } from "@/app/actions/staff-payments";
import { deactivateStaff,updateStaff } from "@/app/actions/staff";
import { randomUUID } from "node:crypto";

export default async function StaffDetail({params}:{params:Promise<{id:string}>}){await requireManagement();const {id}=await params;const [s,users,accounts]=await Promise.all([prisma.staff.findUnique({where:{id},include:{eventAssignments:{where:{active:true},include:{event:{include:{eventType:true,client:true}}},orderBy:{event:{eventDate:"desc"}}},payments:{include:{event:true,createdBy:true},orderBy:{paymentDate:"desc"}}}}),prisma.user.findMany({where:{active:true},orderBy:{name:"asc"},select:{id:true,name:true,email:true}}),prisma.financialAccount.findMany({where:{active:true},orderBy:{name:"asc"}})]);if(!s)notFound();const byCurrency=(currency:"ARS"|"USD")=>calculateStaffFinance(s.eventAssignments.filter(a=>a.currency===currency).map(a=>({amount:String(a.agreedAmount),eventStatus:a.event.status})),s.payments.filter(p=>p.currency===currency).map(p=>({amount:String(p.amount),status:p.status,eventId:p.eventId})));return <><div className="topbar"><div><div className="eyebrow">Personal</div><h1>{s.name}</h1><span className={`badge ${s.active?"badge-green":"badge-warn"}`}>{s.active?"ACTIVO":"INACTIVO"}</span></div><Link className="btn btn-accent" href={`/personal/liquidaciones/${id}`}>Ver liquidación</Link></div><section className="grid grid-2"><FinanceCard currency="ARS" finance={byCurrency("ARS")}/><FinanceCard currency="USD" finance={byCurrency("USD")}/></section><details className="card edit-quote"><summary>Editar datos y tarifa</summary><form action={updateStaff.bind(null,id)} className="form edit-panel"><div className="form-grid"><div className="field"><label>Nombre</label><input name="name" defaultValue={s.name} required/></div><div className="field"><label>Rol habitual</label><select name="defaultRole" defaultValue={s.defaultRole}>{Object.values(StaffRole).map(r=><option key={r}>{r}</option>)}</select></div><div className="field"><label>Teléfono</label><input name="phone" defaultValue={s.phone||""}/></div><div className="field"><label>Email</label><input name="email" type="email" defaultValue={s.email||""}/></div><div className="field"><label>Tarifa estándar</label><input name="defaultEventRate" type="number" min="0" step="0.01" defaultValue={String(s.defaultEventRate)} required/></div><div className="field"><label>Moneda</label><select name="currency" defaultValue={s.currency}><option>ARS</option><option>USD</option></select></div><div className="field"><label>Usuario vinculado</label><select name="userId" defaultValue={s.userId||""}><option value="">Sin usuario</option>{users.map(u=><option key={u.id} value={u.id}>{u.name} · {u.email}</option>)}</select></div><div className="field span-2"><label>Notas</label><textarea name="notes" defaultValue={s.notes||""}/></div></div><button className="btn btn-primary">Guardar datos</button></form></details>
<div className="section-head"><h2>Registrar pago o adelanto</h2></div><form action={createStaffPayment.bind(null,id)} className="card form"><div className="form-grid form-grid-4"><div className="field"><label>Evento</label><select name="eventId"><option value="">Adelanto general</option>{[...new Map(s.eventAssignments.map(a=>[a.eventId,a.event])).values()].map(e=><option key={e.id} value={e.id}>{e.number} · {e.eventDate.toLocaleDateString("es-AR",{timeZone:"UTC"})}</option>)}</select></div><div className="field"><label>Tipo</label><select name="paymentType">{Object.values(PaymentType).map(x=><option key={x}>{x}</option>)}</select></div><div className="field"><label>Importe</label><input name="amount" type="number" min="0.01" step="0.01" required/></div><div className="field"><label>Moneda</label><select name="currency" defaultValue={s.currency}><option>ARS</option><option>USD</option></select></div><div className="field"><label>Cuenta</label><select name="accountId" defaultValue={accounts.find(a=>a.currency===s.currency)?.id||""} required><option value="">Seleccionar</option>{accounts.map(a=><option value={a.id} key={a.id}>{a.name} · {a.currency}</option>)}</select></div><div className="field"><label>Fecha de pago</label><input name="paymentDate" type="date" defaultValue={new Date().toISOString().slice(0,10)} required/></div><div className="field"><label>Método</label><select name="paymentMethod">{Object.values(PaymentMethod).map(x=><option key={x}>{x}</option>)}</select></div><div className="field span-2"><label>Notas</label><input name="notes"/></div></div><input type="hidden" name="idempotencyKey" value={randomUUID()}/><button className="btn btn-primary">Registrar movimiento</button></form>
<div className="section-head"><h2>Eventos y obligaciones</h2></div><div className="stack">{s.eventAssignments.map(a=><Link href={`/eventos/${a.eventId}`} className="card row space" key={a.id}><div><strong>{a.event.number} · {a.event.eventDate.toLocaleDateString("es-AR",{timeZone:"UTC"})}</strong><div className="muted">{a.assignmentType.replaceAll("_"," ")} · {a.event.client.name}</div></div><strong>{formatMoney(String(a.agreedAmount),a.currency)}</strong></Link>)}</div>
<div className="section-head"><h2>Historial de pagos</h2></div><div className="stack">{s.payments.map(p=><article className="card payment-row" key={p.id}><div><strong>{formatMoney(String(p.amount),p.currency)}</strong><div className="muted">{p.paymentDate.toLocaleDateString("es-AR",{timeZone:"UTC"})} · {p.paymentType} · {p.event?.number||"Adelanto general"}</div>{p.status==="VOID"&&<span className="badge badge-warn">ANULADO · {p.voidReason}</span>}</div>{p.status==="ACTIVE"&&<form action={voidStaffPayment.bind(null,p.id)} className="row"><input aria-label="Motivo de anulación" name="voidReason" placeholder="Motivo" required/><button className="btn btn-danger">Anular</button></form>}</article>)}</div>{s.active&&<form action={deactivateStaff.bind(null,id)} className="danger-zone"><button className="btn btn-danger">Desactivar personal</button></form>}</>}
function FinanceCard({currency,finance}:{currency:"ARS"|"USD";finance:ReturnType<typeof calculateStaffFinance>}){return <div className="card totals"><div className="eyebrow">Resumen {currency}</div><R label="Generado exigible" value={formatMoney(finance.generated.toFixed(2),currency)}/><R label="Pagos a eventos" value={formatMoney(finance.eventPaid.toFixed(2),currency)}/><R label="Adelantos generales" value={formatMoney(finance.advances.toFixed(2),currency)}/><R label="Pendiente neto" value={formatMoney(finance.pending.toFixed(2),currency)} final/><R label="Comprometido futuro" value={formatMoney(finance.futureCommitted.toFixed(2),currency)}/></div>}
function R({label,value,final=false}:{label:string;value:string;final?:boolean}){return <div className={`total-row ${final?"total-final":""}`}><span>{label}</span><strong>{value}</strong></div>}
