import { expect, test } from "@playwright/test";
import { PrismaClient } from "@prisma/client";
const db=new PrismaClient(),password=process.env.SEED_DEMO_PASSWORD!;
async function login(page:import("@playwright/test").Page,email:string){await page.goto("/login");await page.getByLabel("Email").fill(email);await page.getByLabel("Contraseña").fill(password);await page.getByRole("button",{name:"Ingresar"}).click();await page.waitForURL(email.startsWith("paddy")?"**/staff":"**/dashboard")}
async function logout(page:import("@playwright/test").Page){await page.locator("form").filter({has:page.getByRole("button",{name:"Salir"})}).getByRole("button",{name:"Salir"}).click();await page.waitForURL("**/login")}
async function assign(page:import("@playwright/test").Page,name:string,type:string,amount:string){await page.getByLabel("Persona").selectOption({label:name});await page.getByLabel("Función").selectOption(type);await page.getByLabel("Importe acordado").fill(amount);await page.getByRole("button",{name:"Asignar persona"}).click();await expect(page.locator(".assignment-list .card").filter({hasText:name})).toBeVisible()}
async function expense(page:import("@playwright/test").Page,category:string,description:string,amount:string){await page.getByRole("button",{name:`+ ${category}`}).click();await page.getByLabel("Descripción").fill(description);await page.getByLabel("Importe",{exact:true}).fill(amount);await page.getByRole("button",{name:"Guardar gasto"}).click();await expect(page.locator(".expense-card").filter({hasText:description})).toBeVisible()}
test.afterAll(()=>db.$disconnect());
test("Sprint 3 rentabilidad, cierre y permisos con PostgreSQL real",async({page})=>{
 await login(page,"miguel@murraydjs.local");const event=await db.event.findFirstOrThrow({where:{sourceQuote:{client:{name:"Cliente Prueba Murray"}}},orderBy:{createdAt:"asc"}});await db.eventExpense.deleteMany({where:{eventId:event.id}});await db.event.update({where:{id:event.id},data:{financialStatus:"OPEN",financialClosedAt:null,financialClosedById:null,status:"REALIZADO"}});await page.goto(`/eventos/${event.id}`);
 await assign(page,"Gonzalo","TECNICO","150000");await assign(page,"Bautista","ARMADO","120000");
 await expense(page,"Combustible","Combustible E2E","40000");await expense(page,"Peajes","Peajes E2E","15000");await expense(page,"Comida","Comida E2E","30000");await expense(page,"CO2","CO2 E2E","200000");await expense(page,"Papelitos","Papelitos E2E","100000");
 await expect(page.locator(".metric-result")).toContainText("4.895.000");await expect(page.getByText("Margen ARS").locator("..")).toContainText(/85[,.]13/);
 await page.getByRole("button",{name:"Cerrar finanzas"}).click();await page.getByRole("button",{name:"Confirmar cierre"}).click();await expect(page.getByText("FINANZAS CLOSED")).toBeVisible();await expect(page.getByText("Guardar gasto")).toHaveCount(0);
 const stored=await db.eventExpense.findMany({where:{eventId:event.id,status:"ACTIVE"}});expect(stored.reduce((sum,x)=>sum+Number(x.amount),0)).toBe(385000);const closed=await db.event.findUniqueOrThrow({where:{id:event.id}});expect(closed.financialStatus).toBe("CLOSED");
 await page.goto("/reportes/rentabilidad?month=12&year=2026&currency=ARS");await expect(page.getByText(event.number).first()).toBeVisible();await expect(page.getByText(/4\.895\.000/).first()).toBeVisible();
 await page.goto(`/eventos/${event.id}`);await page.getByRole("button",{name:"Reabrir finanzas"}).click();await page.getByRole("button",{name:"Confirmar reapertura"}).click();await expect(page.getByText("FINANZAS OPEN")).toBeVisible();const fuel=page.locator(".expense-card").filter({hasText:"Combustible E2E"});await fuel.getByText("Editar gasto").click();await fuel.locator('input[name="amount"]').fill("45000");await fuel.getByRole("button",{name:"Guardar cambios"}).click();await expect(fuel).toContainText("45.000");await page.getByRole("button",{name:"Cerrar finanzas"}).click();await page.getByRole("button",{name:"Confirmar cierre"}).click();
 await logout(page);await login(page,"paddy@murraydjs.local");for(const path of ["/gastos","/reportes/rentabilidad",`/eventos/${event.id}`]){await page.goto(path);await expect(page).toHaveURL(/sin-acceso/)}await page.goto("/staff");await expect(page.getByText(/Venta neta|Resultado|Margen|Gastos directos/)).toHaveCount(0);
 const audit=await db.auditLog.findMany({where:{OR:[{entity:"EventExpense"},{entity:"EventFinancial"}]}});expect(audit.some(x=>x.action==="CREATE"&&x.entity==="EventExpense")).toBe(true);expect(audit.some(x=>x.action==="CLOSE")).toBe(true);expect(audit.some(x=>x.action==="REOPEN")).toBe(true);
});
