import {expect,test} from "@playwright/test";
import {PrismaClient} from "@prisma/client";
const db=new PrismaClient(),password=process.env.SEED_DEMO_PASSWORD!;
async function login(page:import("@playwright/test").Page,email:string){await page.goto("/login");await page.getByLabel("Email").fill(email);await page.getByLabel("Contraseña").fill(password);await page.getByRole("button",{name:"Ingresar"}).click();await page.waitForURL(email.startsWith("paddy")?"**/staff":"**/dashboard")}
async function logout(page:import("@playwright/test").Page){await page.locator("form").filter({has:page.getByRole("button",{name:"Salir"})}).getByRole("button",{name:"Salir"}).click();await page.waitForURL("**/login")}
async function assign(page:import("@playwright/test").Page,name:string,type:string,amount:string){await page.getByLabel("Persona").selectOption({label:name});await page.getByLabel("Función").selectOption(type);await page.getByLabel("Importe acordado").fill(amount);await page.getByRole("button",{name:"Asignar persona"}).click();await expect(page.locator(".assignment-list .card").filter({hasText:name})).toBeVisible()}
test.afterAll(()=>db.$disconnect());
test("Sprint 2 personal, pagos y permisos con PostgreSQL real",async({page})=>{
  await login(page,"miguel@murraydjs.local");const gonzalo=await db.staff.findFirstOrThrow({where:{name:"Gonzalo"}});await db.staffPayment.deleteMany({where:{staffId:gonzalo.id}});const event=await db.event.findFirstOrThrow({where:{sourceQuote:{client:{name:"Cliente Prueba Murray"}}}});await page.goto(`/eventos/${event.id}`);
  await page.getByLabel("Encargado operativo").selectOption({label:"Maicky"});await page.getByRole("button",{name:"Guardar encargado"}).click();
  await assign(page,"Maicky","DJ","200000");await assign(page,"Gonzalo","TECNICO","120000");await assign(page,"Bautista","ARMADO","100000");await assign(page,"Paddy","DJ_TECNICO","0");
  await page.getByLabel("Estado del evento").selectOption("REALIZADO");await page.getByRole("button",{name:"Actualizar estado"}).click();await expect(page.getByText("REALIZADO",{exact:true}).first()).toBeVisible();
  await page.goto("/personal/liquidaciones?month=2026-12&currency=ARS");const gRow=page.locator(".settlement-row").filter({hasText:"Gonzalo"});await expect(gRow).toContainText("$ 120.000");await Promise.all([page.waitForURL("**/personal/liquidaciones/**"),gRow.click()]);
  await expect(page.getByText("Pendiente neto").locator("..")).toContainText("$ 120.000");
  await page.goto(`/personal/${gonzalo.id}`);const payment=page.locator("form").filter({has:page.getByRole("button",{name:"Registrar movimiento"})});
  await payment.locator('[name="eventId"]').selectOption("");await payment.locator('[name="paymentType"]').selectOption("ADVANCE");await payment.locator('[name="amount"]').fill("20000");await payment.locator('[name="paymentDate"]').fill("2026-12-15");await payment.getByRole("button",{name:"Registrar movimiento"}).click();await expect(page.locator(".payment-row").filter({hasText:"$ 20.000"})).toBeVisible();
  const payment2=page.locator("form").filter({has:page.getByRole("button",{name:"Registrar movimiento"})});await payment2.locator('[name="eventId"]').selectOption(event.id);await payment2.locator('[name="paymentType"]').selectOption("PARTIAL");await payment2.locator('[name="amount"]').fill("50000");await payment2.locator('[name="paymentDate"]').fill("2026-12-16");await payment2.getByRole("button",{name:"Registrar movimiento"}).click();await expect(page.locator(".payment-row").filter({hasText:"$ 50.000"})).toBeVisible();
  await page.goto(`/personal/liquidaciones/${gonzalo.id}?month=2026-12&currency=ARS`);await expect(page.getByText("Pendiente neto").locator("..")).toContainText("$ 50.000");await expect(page.getByText("Adelantos generales",{exact:true}).locator("..")).toContainText("$ 20.000");
  const payments=await db.staffPayment.findMany({where:{staffId:gonzalo.id},orderBy:{amount:"asc"}});expect(payments).toHaveLength(2);await page.goto(`/personal/${gonzalo.id}`);const paymentCard=page.locator(".payment-row").filter({hasText:"$ 20.000"});await paymentCard.getByLabel("Motivo de anulación").fill("Carga duplicada E2E");await paymentCard.getByRole("button",{name:"Anular"}).click();await expect(paymentCard.getByText(/ANULADO/)).toBeVisible();expect((await db.staffPayment.findUniqueOrThrow({where:{id:payments[0].id}})).status).toBe("VOID");
  await logout(page);await login(page,"paddy@murraydjs.local");await expect(page.getByText(event.number)).toBeVisible();await expect(page.getByText("Tu función").locator("..")).toContainText("DJ TECNICO");await expect(page.getByText(/\$|Importe acordado|Pagos/)).toHaveCount(0);
  for(const path of ["/personal","/personal/liquidaciones",`/eventos/${event.id}`]){await page.goto(path);await expect(page).toHaveURL(/sin-acceso/)}
  const audit=await db.auditLog.findMany({where:{OR:[{entity:"EventStaff"},{entity:"StaffPayment"}]}});expect(audit.some(x=>x.action==="ASSIGN")).toBe(true);expect(audit.some(x=>x.action==="CREATE"&&x.entity==="StaffPayment")).toBe(true);expect(audit.some(x=>x.action==="VOID")).toBe(true);
});
