import Link from "next/link";
import { Currency, Prisma, QuoteStatus } from "@prisma/client";
import { prisma } from "@/server/db/prisma";
import { formatMoney } from "@/lib/money/format";
import { requireManagement } from "@/server/auth/authorization";
import { calculateStaffFinance } from "@/lib/staff/finance";
import { findStaffConflicts } from "@/lib/staff/conflicts";
import { calculateEventProfitability } from "@/lib/profitability/event-profitability";
import { treasurySummary } from "@/server/treasury/summary";

type Filters={from?:string;to?:string;eventTypeId?:string;status?:string;clientId?:string;currency?:string;q?:string};
export default async function Dashboard({searchParams}:{searchParams:Promise<Filters>}) {
  await requireManagement(); const p=await searchParams; const now=new Date();
  const from=p.from||`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,"0")}-01`;
  const last=new Date(Date.UTC(now.getFullYear(),now.getMonth()+1,0)).getUTCDate(); const to=p.to||`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,"0")}-${last}`;
  const dateFilter={gte:new Date(`${from}T00:00:00.000Z`),lte:new Date(`${to}T00:00:00.000Z`)};
  const quoteWhere:Prisma.QuoteWhereInput={eventDate:dateFilter,eventTypeId:p.eventTypeId||undefined,clientId:p.clientId||undefined,status:Object.values(QuoteStatus).includes(p.status as QuoteStatus)?p.status as QuoteStatus:undefined,OR:p.q?[{number:{contains:p.q,mode:"insensitive"}},{venue:{contains:p.q,mode:"insensitive"}},{client:{name:{contains:p.q,mode:"insensitive"}}}]:undefined};
  const eventWhere:Prisma.EventWhereInput={eventDate:dateFilter,eventTypeId:p.eventTypeId||undefined,clientId:p.clientId||undefined,OR:p.q?[{number:{contains:p.q,mode:"insensitive"}},{venue:{contains:p.q,mode:"insensitive"}},{client:{name:{contains:p.q,mode:"insensitive"}}}]:undefined};
  const [confirmed,events,waiting,eventTypes,clients,assignments,payments,profitEvents,treasury]=await Promise.all([
    prisma.quote.findMany({where:{...quoteWhere,confirmedVersionId:{not:null},confirmedVersion:{currency:Object.values(Currency).includes(p.currency as Currency)?p.currency as Currency:undefined}},select:{confirmedVersion:{select:{currency:true,totalFinal:true}}}}),
    prisma.event.findMany({where:eventWhere,include:{client:true,eventType:true,_count:{select:{staffAssignments:{where:{active:true}}}}},orderBy:{eventDate:"asc"},take:20}),
    prisma.quote.count({where:{...quoteWhere,status:"ESPERANDO_SENA"}}),
    prisma.eventType.findMany({where:{active:true},orderBy:{name:"asc"}}),prisma.client.findMany({where:{active:true},orderBy:{name:"asc"},select:{id:true,name:true}}),
    prisma.eventStaff.findMany({where:{active:true},include:{event:true,staff:true}}),prisma.staffPayment.findMany({where:{status:"ACTIVE"}}),
    prisma.event.findMany({where:eventWhere,include:{client:true,sourceQuoteVersion:true,staffAssignments:{where:{active:true}},expenses:{where:{status:"ACTIVE"}}}}),treasurySummary()
  ]);
  const totals={ARS:0,USD:0}; confirmed.forEach(q=>{if(q.confirmedVersion)totals[q.confirmedVersion.currency]+=Number(q.confirmedVersion.totalFinal)});
  const staffTotals={ARS:{pending:0,future:0},USD:{pending:0,future:0}};for(const currency of Object.values(Currency)){const f=calculateStaffFinance(assignments.filter(a=>a.currency===currency).map(a=>({amount:String(a.agreedAmount),eventStatus:a.event.status,eventId:a.eventId})),payments.filter(x=>x.currency===currency).map(x=>({amount:String(x.amount),status:x.status,eventId:x.eventId})));staffTotals[currency]={pending:Number(f.pending),future:Number(f.futureCommitted)}}
  const unassigned=events.filter(e=>e._count.staffAssignments===0);const conflictGroups=new Map<string,typeof assignments>();assignments.forEach(a=>conflictGroups.set(a.staffId,[...(conflictGroups.get(a.staffId)||[]),a]));const conflicts=[...conflictGroups.values()].flatMap(group=>findStaffConflicts([...new Map(group.map(a=>[a.eventId,{id:a.event.id,number:a.event.number,eventDate:a.event.eventDate.toISOString().slice(0,10),startTime:a.event.startTime,endTime:a.event.endTime,setupTime:a.event.setupTime}])).values()]).map(pair=>({staff:group[0].staff.name,...pair})));
  const profitability=profitEvents.map(event=>({event,profit:calculateEventProfitability({version:event.sourceQuoteVersion,assignments:event.staffAssignments,expenses:event.expenses})}));const closed=profitability.filter(x=>x.event.financialStatus==="CLOSED"),pendingClose=profitEvents.filter(x=>["REALIZADO","CERRADO"].includes(x.status)&&x.financialStatus!=="CLOSED");const financialTotals={ARS:{sale:0,staff:0,expenses:0,result:0},USD:{sale:0,staff:0,expenses:0,result:0}};for(const row of closed)for(const currency of Object.values(Currency)){const p=row.profit.byCurrency[currency];financialTotals[currency].sale+=Number(p.netSale);financialTotals[currency].staff+=Number(p.staffCost);financialTotals[currency].expenses+=Number(p.directExpenses);financialTotals[currency].result+=Number(p.result)}
  return <><div className="topbar"><div><div className="eyebrow">Resumen</div><h1>Todo bajo control</h1></div><Link className="btn btn-accent" href="/presupuestos/nuevo">+ Presupuesto</Link></div>
    <details className="card filters" open><summary>Filtros del dashboard</summary><form method="get" className="filter-grid"><div className="field"><label htmlFor="filter-from">Desde</label><input id="filter-from" name="from" type="date" defaultValue={from}/></div><div className="field"><label htmlFor="filter-to">Hasta</label><input id="filter-to" name="to" type="date" defaultValue={to}/></div><div className="field"><label htmlFor="filter-type">Tipo de evento</label><select id="filter-type" name="eventTypeId" defaultValue={p.eventTypeId||""}><option value="">Todos</option>{eventTypes.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></div><div className="field"><label htmlFor="filter-status">Estado</label><select id="filter-status" name="status" defaultValue={p.status||""}><option value="">Todos</option>{Object.values(QuoteStatus).map(s=><option key={s} value={s}>{s.replaceAll("_"," ")}</option>)}</select></div><div className="field"><label htmlFor="filter-client">Cliente</label><select id="filter-client" name="clientId" defaultValue={p.clientId||""}><option value="">Todos</option>{clients.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></div><div className="field"><label htmlFor="filter-currency">Moneda</label><select id="filter-currency" name="currency" defaultValue={p.currency||""}><option value="">Todas</option><option>ARS</option><option>USD</option></select></div><div className="field filter-search"><label htmlFor="filter-q">Buscar</label><input id="filter-q" name="q" defaultValue={p.q||""} placeholder="Número, cliente o lugar"/></div><div className="filter-actions"><button className="btn btn-primary">Aplicar filtros</button><Link className="btn btn-secondary" href="/dashboard">Limpiar</Link></div></form></details>
    <section className="grid grid-4 metrics"><div className="card metric"><span>Confirmado · ARS</span><strong>{formatMoney(totals.ARS,"ARS")}</strong></div><div className="card metric"><span>Confirmado · USD</span><strong>{formatMoney(totals.USD,"USD")}</strong></div><div className="card metric"><span>Eventos del período</span><strong>{events.length}</strong></div><div className="card metric"><span>Esperando seña</span><strong>{waiting}</strong></div><div className="card metric"><span>Personal pendiente · ARS</span><strong>{formatMoney(staffTotals.ARS.pending,"ARS")}</strong></div><div className="card metric"><span>Personal pendiente · USD</span><strong>{formatMoney(staffTotals.USD.pending,"USD")}</strong></div><div className="card metric"><span>Compromisos futuros · ARS</span><strong>{formatMoney(staffTotals.ARS.future,"ARS")}</strong></div><div className="card metric"><span>Compromisos futuros · USD</span><strong>{formatMoney(staffTotals.USD.future,"USD")}</strong></div></section>
    <div className="section-head"><h2>Caja y tesorería</h2><Link href="/tesoreria">Ver tesorería →</Link></div>{(["ARS","USD"] as const).map(currency=><section className="grid grid-4 metrics" key={`cash-${currency}`}><div className="card metric"><span>Saldo en cuentas · {currency}</span><strong>{formatMoney(treasury.buckets[currency].availableCash.toFixed(2),currency)}</strong></div><div className="card metric"><span>Por cobrar · {currency}</span><strong>{formatMoney(treasury.buckets[currency].receivable.toFixed(2),currency)}</strong></div><div className="card metric"><span>Por pagar · {currency}</span><strong>{formatMoney(treasury.buckets[currency].payable.toFixed(2),currency)}</strong></div><div className="card metric metric-result"><span>Disponibilidad estimada · {currency}</span><strong>{formatMoney(treasury.buckets[currency].estimated.toFixed(2),currency)}</strong></div></section>)}
    <div className="section-head"><h2>Resultado definitivo · eventos cerrados</h2><Link href={`/reportes/rentabilidad`}>Ver reporte →</Link></div>{(["ARS","USD"] as const).map(currency=><section className="profit-grid" key={currency}><div className="card metric"><span>Facturación neta · {currency}</span><strong>{formatMoney(financialTotals[currency].sale,currency)}</strong></div><div className="card metric"><span>Personal · {currency}</span><strong>{formatMoney(financialTotals[currency].staff,currency)}</strong></div><div className="card metric"><span>Gastos directos · {currency}</span><strong>{formatMoney(financialTotals[currency].expenses,currency)}</strong></div><div className="card metric metric-result"><span>Resultado · {currency}</span><strong>{formatMoney(financialTotals[currency].result,currency)}</strong></div><div className="card metric"><span>Margen · {currency}</span><strong>{financialTotals[currency].sale>0?`${(financialTotals[currency].result/financialTotals[currency].sale*100).toFixed(2)}%`:"—"}</strong></div></section>)}
    <section className="grid grid-2 metrics"><div className="card metric"><span>Eventos cerrados financieramente</span><strong>{closed.length}</strong></div><div className="card metric"><span>Realizados pendientes de cierre</span><strong>{pendingClose.length}</strong></div></section>
    {pendingClose.length>0&&<div className="alert alert-warn"><strong>EVENTOS REALIZADOS SIN CIERRE FINANCIERO</strong><p>{pendingClose.map(e=>e.number).join(", ")}</p></div>}
    {(unassigned.length>0||conflicts.length>0)&&<section className="alert-stack">{unassigned.length>0&&<div className="alert alert-warn"><strong>EVENTO SIN PERSONAL ASIGNADO</strong><p>{unassigned.map(e=>e.number).join(", ")}</p></div>}{conflicts.length>0&&<div className="alert alert-danger"><strong>CONFLICTO DE PERSONAL</strong>{conflicts.map((c,i)=><p key={`${c.staff}-${i}`}>{c.staff}: {c.first.number} / {c.second.number}</p>)}</div>}</section>}
    <div className="section-head"><h2>Eventos del período</h2><Link href="/agenda">Ver agenda →</Link></div><div className="table-wrap"><table className="table"><thead><tr><th>Fecha</th><th>Evento</th><th>Cliente</th><th>Lugar</th><th>Horario</th></tr></thead><tbody>{events.map(e=><tr key={e.id}><td data-label="Fecha">{e.eventDate.toLocaleDateString("es-AR",{timeZone:"UTC"})}</td><td data-label="Evento"><Link href={`/eventos/${e.id}`}>{e.eventType.name}</Link></td><td data-label="Cliente">{e.client.name}</td><td data-label="Lugar">{e.venue}</td><td data-label="Horario">{e.startTime}–{e.endTime}</td></tr>)}{!events.length&&<tr><td colSpan={5} className="empty">No hay eventos para estos filtros.</td></tr>}</tbody></table></div></>;
}
