import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { PrismaClient } from "@prisma/client";
import { calculateEventProfitability } from "@/lib/profitability/event-profitability";

const db=new PrismaClient(),run=process.env.RUN_DB_INTEGRATION==="true";
let ids:{event:string;quote:string;version:string;client:string;category:string;expense?:string;user:string};
describe.runIf(run)("expense and financial close workflow with PostgreSQL",()=>{
 beforeAll(async()=>{const suffix=`EXP-${Date.now()}`,user=await db.user.findFirstOrThrow({where:{role:"ADMIN"}}),type=await db.eventType.findFirstOrThrow(),category=await db.expenseCategory.findFirstOrThrow({where:{slug:"combustible"}});const client=await db.client.create({data:{name:suffix,type:"PARTICULAR"}});const quote=await db.quote.create({data:{number:`PRE-${suffix}`,clientId:client.id,eventTypeId:type.id,eventDate:new Date("2027-06-10T00:00:00Z"),venue:"Integration expense",startTime:"21:00",endTime:"03:00",createdById:user.id,status:"CONFIRMADO"}});const version=await db.quoteVersion.create({data:{quoteId:quote.id,versionNumber:1,currency:"ARS",grossSubtotal:5750000,itemDiscountTotal:0,subtotalAfterItemDiscounts:5750000,generalDiscountValue:0,generalDiscountAmount:0,taxableBase:5750000,taxRate:0,taxAmount:0,totalFinal:5750000,depositPercentage:50,depositAmount:2875000,balance:2875000,createdById:user.id}});const event=await db.event.create({data:{number:`EVT-${suffix}`,clientId:client.id,eventTypeId:type.id,sourceQuoteId:quote.id,sourceQuoteVersionId:version.id,eventDate:quote.eventDate,startTime:"21:00",endTime:"03:00",setupTime:"18:30",venue:"Integration expense",status:"REALIZADO"}});ids={event:event.id,quote:quote.id,version:version.id,client:client.id,category:category.id,user:user.id}});
 afterAll(async()=>{if(ids){await db.auditLog.deleteMany({where:{entityId:{in:[ids.event,ids.expense||""]}}});await db.eventExpense.deleteMany({where:{eventId:ids.event}});await db.event.delete({where:{id:ids.event}});await db.quoteVersion.delete({where:{id:ids.version}});await db.quote.delete({where:{id:ids.quote}});await db.client.delete({where:{id:ids.client}})}await db.$disconnect()});
 it("creates, edits and voids without physical deletion",async()=>{const expense=await db.eventExpense.create({data:{eventId:ids.event,categoryId:ids.category,description:"Nafta",amount:40000,currency:"ARS",expenseDate:new Date("2027-06-10T00:00:00Z"),paymentMethod:"CASH",createdById:ids.user}});ids.expense=expense.id;await db.eventExpense.update({where:{id:expense.id},data:{amount:45000,notes:"corregido"}});await db.eventExpense.update({where:{id:expense.id},data:{status:"VOID",voidedAt:new Date(),voidedById:ids.user,voidReason:"duplicado"}});expect(await db.eventExpense.count({where:{id:expense.id}})).toBe(1);expect((await db.eventExpense.findUniqueOrThrow({where:{id:expense.id}})).status).toBe("VOID")});
it("VOID is excluded, then reopen allows a new active cost and recalculate",async()=>{await db.event.update({where:{id:ids.event},data:{financialStatus:"CLOSED",financialClosedAt:new Date(),financialClosedById:ids.user}});expect((await db.event.findUniqueOrThrow({where:{id:ids.event}})).financialStatus).toBe("CLOSED");await db.event.update({where:{id:ids.event},data:{financialStatus:"OPEN",financialClosedAt:null,financialClosedById:null}});await db.eventExpense.create({data:{eventId:ids.event,categoryId:ids.category,description:"Peaje",amount:15000,currency:"ARS",expenseDate:new Date("2027-06-10T00:00:00Z"),createdById:ids.user}});const event=await db.event.findUniqueOrThrow({where:{id:ids.event},include:{sourceQuoteVersion:true,staffAssignments:true,expenses:true}});if(!event.sourceQuoteVersion)throw new Error("Fixture without source quote version");const p=calculateEventProfitability({version:event.sourceQuoteVersion,assignments:event.staffAssignments,expenses:event.expenses});expect(p.byCurrency.ARS.directExpenses.toFixed(2)).toBe("15000.00");await db.event.update({where:{id:ids.event},data:{financialStatus:"CLOSED",financialClosedAt:new Date(),financialClosedById:ids.user}});expect((await db.event.findUniqueOrThrow({where:{id:ids.event}})).financialStatus).toBe("CLOSED")});
});
