import {afterAll,beforeAll,describe,expect,it} from "vitest";
import {PrismaClient} from "@prisma/client";
const db=new PrismaClient();const run=process.env.RUN_DB_INTEGRATION==="true";let ids:{staff:string;event:string;quote:string;version:string;client:string;user:string};
describe.runIf(run)("staff workflow with PostgreSQL",()=>{
  beforeAll(async()=>{const suffix=`IT-${Date.now()}`,user=await db.user.findFirstOrThrow({where:{role:"ADMIN"}}),type=await db.eventType.findFirstOrThrow();const client=await db.client.create({data:{name:suffix,type:"PARTICULAR"}});const quote=await db.quote.create({data:{number:`PRE-${suffix}`,clientId:client.id,eventTypeId:type.id,eventDate:new Date("2027-05-10T00:00:00Z"),venue:"Integration",startTime:"21:00",endTime:"03:00",createdById:user.id}});const version=await db.quoteVersion.create({data:{quoteId:quote.id,versionNumber:1,currency:"ARS",grossSubtotal:0,itemDiscountTotal:0,subtotalAfterItemDiscounts:0,generalDiscountValue:0,generalDiscountAmount:0,taxableBase:0,taxRate:0,taxAmount:0,totalFinal:0,depositPercentage:50,depositAmount:0,balance:0,createdById:user.id}});const event=await db.event.create({data:{number:`EVT-${suffix}`,clientId:client.id,eventTypeId:type.id,sourceQuoteId:quote.id,sourceQuoteVersionId:version.id,eventDate:quote.eventDate,startTime:"21:00",endTime:"03:00",setupTime:"18:30",venue:"Integration"}});const staff=await db.staff.create({data:{name:suffix,defaultRole:"TECNICO",defaultEventRate:100000,currency:"ARS"}});ids={staff:staff.id,event:event.id,quote:quote.id,version:version.id,client:client.id,user:user.id}});
  afterAll(async()=>{if(ids){await db.staffPayment.deleteMany({where:{staffId:ids.staff}});await db.eventStaff.deleteMany({where:{staffId:ids.staff}});await db.event.delete({where:{id:ids.event}});await db.quoteVersion.delete({where:{id:ids.version}});await db.quote.delete({where:{id:ids.quote}});await db.staff.delete({where:{id:ids.staff}});await db.client.delete({where:{id:ids.client}})}await db.$disconnect()});
  it("assigns and preserves the agreed snapshot when the default rate changes",async()=>{const a=await db.eventStaff.create({data:{eventId:ids.event,staffId:ids.staff,assignmentType:"TECNICO",agreedAmount:100000,currency:"ARS",createdById:ids.user}});await db.staff.update({where:{id:ids.staff},data:{defaultEventRate:120000}});expect(String((await db.eventStaff.findUniqueOrThrow({where:{id:a.id}})).agreedAmount)).toBe("100000")});
  it("updates agreed amount, records partial payments and voids without deleting",async()=>{const a=await db.eventStaff.findFirstOrThrow({where:{staffId:ids.staff}});await db.eventStaff.update({where:{id:a.id},data:{agreedAmount:110000}});const first=await db.staffPayment.create({data:{staffId:ids.staff,eventId:ids.event,amount:40000,currency:"ARS",paymentDate:new Date("2027-05-11T00:00:00Z"),paymentMethod:"TRANSFER",paymentType:"PARTIAL",createdById:ids.user}});await db.staffPayment.create({data:{staffId:ids.staff,eventId:ids.event,amount:30000,currency:"ARS",paymentDate:new Date("2027-05-12T00:00:00Z"),paymentMethod:"CASH",paymentType:"PARTIAL",createdById:ids.user}});await db.staffPayment.update({where:{id:first.id},data:{status:"VOID",voidedAt:new Date(),voidedById:ids.user,voidReason:"Integration test"}});expect(await db.staffPayment.count({where:{staffId:ids.staff}})).toBe(2);expect(await db.staffPayment.count({where:{staffId:ids.staff,status:"ACTIVE"}})).toBe(1);expect(String((await db.eventStaff.findUniqueOrThrow({where:{id:a.id}})).agreedAmount)).toBe("110000")});
});
