const labels: Record<string, string> = {
  ADMIN: "Administrador",
  ADMIN_FINANCIERO: "Administración financiera",
  STAFF: "Personal",
  CONFIRMADO: "Confirmado",
  EN_PREPARACION: "En preparación",
  LISTO: "Listo",
  EN_CURSO: "En curso",
  REALIZADO: "Realizado",
  CERRADO: "Cerrado",
  CANCELADO: "Cancelado",
  PENDIENTE: "Pendiente",
  READY_TO_CLOSE: "Listo para cerrar",
  CLOSED: "Cerrado",
  ACTIVE: "Activo",
  INACTIVE: "Inactivo",
  VOID: "Anulado",
  CONSULTA: "Consulta",
  PRESUPUESTO_ENVIADO: "Presupuesto enviado",
  EN_NEGOCIACION: "En negociación",
  ESPERANDO_SENA: "Esperando seña",
  OPERATING: "Operativo",
  INVESTMENT: "Inversión",
  PARTICULAR: "Particular",
  EMPRESA: "Empresa",
  DJ_TECNICO: "DJ técnico",
  TECNICO: "Técnico",
  DJ: "DJ",
  ADVANCE: "Adelanto",
  PARTIAL: "Parcial",
  FINAL: "Final",
  TRANSFER: "Transferencia",
  CASH: "Efectivo",
  OTHER: "Otro",
  BANK: "Banco",
  MERCADO_PAGO: "Mercado Pago",
  THIRD_PARTY: "Fondos de terceros",
  INFLOW: "Ingreso",
  OUTFLOW: "Egreso",
  OPENING_BALANCE: "Saldo inicial",
  CLIENT_PAYMENT: "Cobro de cliente",
  STAFF_PAYMENT: "Pago a personal",
  EVENT_EXPENSE: "Gasto de evento",
  GENERAL_EXPENSE: "Gasto general",
  REIMBURSEMENT: "Reintegro",
  OWNER_WITHDRAWAL: "Retiro de socios",
  OWNER_CONTRIBUTION: "Aporte de socios",
  ADJUSTMENT: "Ajuste",
};

export function humanLabel(value: string) {
  if (labels[value]) return labels[value];
  const normalized = value.replaceAll("_", " ").toLocaleLowerCase("es-AR");
  return normalized.charAt(0).toLocaleUpperCase("es-AR") + normalized.slice(1);
}
