import { randomUUID } from "node:crypto";
import Link from "next/link";
import { prisma } from "@/server/db/prisma";
import { requireManagement } from "@/server/auth/authorization";
import { formatMoney } from "@/lib/money/format";
import { createExpenseCategory, updateExpenseCategory } from "@/app/actions/expenses";
import { EmptyState, PageHeader } from "@/components/ui";
import { createGeneralExpense, voidGeneralExpense } from "@/app/actions/general-expenses";

export default async function ExpensesPage(){await requireManagement();const [categories,expenses,generalExpenses,accounts,staff]=await Promise.all([prisma.expenseCategory.findMany({orderBy:[{sortOrder:"asc"},{name:"asc"}]}),prisma.eventExpense.findMany({take:30,orderBy:{createdAt:"desc"},include:{event:true,category:true,paidByStaff:true}}),prisma.generalExpense.findMany({take:30,orderBy:{createdAt:"desc"},include:{category:true,account:true,paidByStaff:true}}),prisma.financialAccount.findMany({where:{active:true},orderBy:{name:"asc"}}),prisma.staff.findMany({where:{active:true},orderBy:{name:"asc"}})]);return <>
 <PageHeader eyebrow="Finanzas" title="Gastos" description="Categorías configurables y últimos gastos directos."/>
 <section className="grid grid-2"><div className="card"><h2>Nueva categoría</h2><form action={createExpenseCategory} className="form"><div className="field"><label>Nombre</label><input name="name" required/></div><div className="field"><label>Slug</label><input name="slug" placeholder="ej. mantenimiento" required/></div><div className="field"><label>Orden</label><input name="sortOrder" type="number" defaultValue="100"/></div><button className="btn btn-primary">Crear categoría</button></form></div><div className="card"><h2>Categorías</h2><div className="category-list">{categories.map(c=><form key={c.id} action={updateExpenseCategory.bind(null,c.id)} className="category-row"><input name="name" defaultValue={c.name} aria-label={`Nombre ${c.name}`}/><input name="sortOrder" type="number" defaultValue={c.sortOrder} aria-label={`Orden ${c.name}`}/><select name="active" defaultValue={String(c.active)} aria-label={`Estado ${c.name}`}><option value="true">Activa</option><option value="false">Inactiva</option></select><button className="btn btn-secondary">Guardar</button></form>)}</div></div></section>
 <div className="section-head"><h2>Gastos generales e inversiones</h2></div><section className="card"><form action={createGeneralExpense} className="form"><div className="form-grid"><div className="field"><label>Categoría</label><select name="categoryId" required><option value="">Seleccionar</option>{categories.filter(c=>c.active&&["GENERAL","BOTH"].includes(c.scope)).map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></div><div className="field"><label>Descripción</label><input name="description" required/></div><div className="field"><label>Importe</label><input name="amount" type="number" min="0.01" step="0.01" required/></div><div className="field"><label>Moneda</label><select name="currency"><option>ARS</option><option>USD</option></select></div><div className="field"><label>Fecha</label><input name="expenseDate" type="date" defaultValue={new Date().toISOString().slice(0,10)} required/></div><div className="field"><label>Clasificación</label><select name="type"><option value="OPERATING">Operativo</option><option value="INVESTMENT">Inversión</option></select></div><div className="field"><label>Cuenta Murray</label><select name="accountId"><option value="">No pagó Murray</option>{accounts.map(a=><option value={a.id} key={a.id}>{a.name} · {a.currency}</option>)}</select></div><div className="field"><label>Pagó personalmente</label><select name="paidByStaffId"><option value="">No aplica</option>{staff.map(s=><option value={s.id} key={s.id}>{s.name}</option>)}</select></div><div className="field span-2"><label>Notas</label><input name="notes"/></div></div><input name="idempotencyKey" type="hidden" value={randomUUID()}/><button className="btn btn-primary">Registrar gasto general</button></form></section>
 <section className="expense-list">{generalExpenses.map(x=><article className={`card expense-card ${x.status==="VOID"?"expense-void":""}`} key={x.id}><div><span className="badge">{x.type}</span><h3>{x.description}</h3><p className="muted">{x.category.name} · {x.account?.name||x.paidByStaff?.name||"Sin pagador"}</p></div><strong>{formatMoney(String(x.amount),x.currency)}</strong>{x.status==="ACTIVE"&&<form action={voidGeneralExpense.bind(null,x.id)} className="row"><input name="voidReason" placeholder="Motivo" required/><button className="btn btn-danger">Anular</button></form>}</article>)}</section>
 <div className="section-head"><h2>Últimos gastos de eventos</h2></div><section className="expense-list">{expenses.map(x=><Link href={`/eventos/${x.eventId}`} className={`card expense-card card-interactive ${x.status==="VOID"?"expense-void":""}`} key={x.id}><div><span className="badge">{x.category.name}</span><h3>{x.description}</h3><p className="muted">{x.event.number} · Pagó {x.paidByStaff?.name||(x.accountId?"Murray DJs":"sin informar")}</p></div><strong>{formatMoney(String(x.amount),x.currency)}</strong></Link>)}{!expenses.length&&<EmptyState title="Todavía no hay gastos" description="Cargalos desde la ficha de cada evento."/>}</section>
 </>}
