import { randomUUID } from "node:crypto";
import Link from "next/link";
import { createExpenseCategory, updateExpenseCategory } from "@/app/actions/expenses";
import { createGeneralExpense, voidGeneralExpense } from "@/app/actions/general-expenses";
import { formatMoney } from "@/lib/money/format";
import { humanLabel } from "@/lib/ui/labels";
import { requireManagement } from "@/server/auth/authorization";
import { prisma } from "@/server/db/prisma";

export default async function ExpensesPage() {
  await requireManagement();
  const [categories, expenses, generalExpenses, accounts, staff] = await Promise.all([
    prisma.expenseCategory.findMany({ orderBy: [{ sortOrder: "asc" }, { name: "asc" }] }),
    prisma.eventExpense.findMany({ take: 30, orderBy: { createdAt: "desc" }, include: { event: true, category: true, paidByStaff: true } }),
    prisma.generalExpense.findMany({ take: 30, orderBy: { createdAt: "desc" }, include: { category: true, account: true, paidByStaff: true } }),
    prisma.financialAccount.findMany({ where: { active: true }, orderBy: { name: "asc" } }),
    prisma.staff.findMany({ where: { active: true }, orderBy: { name: "asc" } }),
  ]);

  return <>
    <div className="topbar"><div><h1>Gastos</h1><p className="muted">Egresos generales, inversiones y costos vinculados a eventos.</p></div><a className="btn btn-primary" href="#registrar-gasto">+ Registrar gasto</a></div>
    <section className="expense-workspace">
      <div className="operation-panel" id="registrar-gasto"><div className="panel-heading"><div><h2>Registrar gasto general</h2><p>Para gastos que no pertenecen a un evento puntual.</p></div></div><form action={createGeneralExpense} className="form"><div className="form-grid"><div className="field"><label>Categoría</label><select name="categoryId" required><option value="">Seleccionar</option>{categories.filter((category) => category.active && ["GENERAL", "BOTH"].includes(category.scope)).map((category) => <option value={category.id} key={category.id}>{category.name}</option>)}</select></div><div className="field"><label>Descripción</label><input name="description" required /></div><div className="field"><label>Importe</label><input name="amount" type="number" min="0.01" step="0.01" required /></div><div className="field"><label>Moneda</label><select name="currency"><option>ARS</option><option>USD</option></select></div><div className="field"><label>Fecha</label><input name="expenseDate" type="date" defaultValue={new Date().toISOString().slice(0, 10)} required /></div><div className="field"><label>Clasificación</label><select name="type"><option value="OPERATING">Operativo</option><option value="INVESTMENT">Inversión</option></select></div><div className="field"><label>Cuenta Murray</label><select name="accountId"><option value="">No pagó Murray</option>{accounts.map((account) => <option value={account.id} key={account.id}>{account.name} · {account.currency}</option>)}</select></div><div className="field"><label>Pagó personalmente</label><select name="paidByStaffId"><option value="">No aplica</option>{staff.map((person) => <option value={person.id} key={person.id}>{person.name}</option>)}</select></div><div className="field span-2"><label>Notas</label><input name="notes" /></div></div><input name="idempotencyKey" type="hidden" value={randomUUID()} /><button className="btn btn-primary">Registrar gasto general</button></form></div>
      <div className="ledger-panel"><div className="panel-heading"><div><h2>Gastos generales recientes</h2><p>Últimos movimientos registrados.</p></div></div><div className="expense-ledger">{generalExpenses.map((expense) => <article className={expense.status === "VOID" ? "expense-void" : ""} key={expense.id}><div><span className="badge">{humanLabel(expense.type)}</span><strong>{expense.description}</strong><small>{expense.category.name} · {expense.account?.name || expense.paidByStaff?.name || "Sin pagador"}</small></div><strong>{formatMoney(String(expense.amount), expense.currency)}</strong>{expense.status === "ACTIVE" && <details className="row-action"><summary>Anular</summary><form action={voidGeneralExpense.bind(null, expense.id)}><input name="voidReason" placeholder="Motivo de anulación" aria-label="Motivo de anulación" required /><button className="btn btn-danger">Confirmar</button></form></details>}</article>)}{!generalExpenses.length && <div className="empty-inline">Todavía no hay gastos generales.</div>}</div></div>
    </section>

    <details className="settings-panel"><summary><span><strong>Categorías de gastos</strong><small>{categories.filter((category) => category.active).length} categorías activas</small></span><span>Administrar</span></summary><div className="settings-content"><form action={createExpenseCategory} className="form compact-form"><div className="form-grid form-grid-4"><div className="field"><label>Nombre</label><input name="name" required /></div><div className="field"><label>Slug</label><input name="slug" placeholder="ej. mantenimiento" required /></div><div className="field"><label>Orden</label><input name="sortOrder" type="number" defaultValue="100" /></div><button className="btn btn-secondary">Crear categoría</button></div></form><div className="category-list">{categories.map((category) => <form key={category.id} action={updateExpenseCategory.bind(null, category.id)} className="category-row"><input name="name" defaultValue={category.name} aria-label={`Nombre ${category.name}`} /><input name="sortOrder" type="number" defaultValue={category.sortOrder} aria-label={`Orden ${category.name}`} /><select name="active" defaultValue={String(category.active)} aria-label={`Estado ${category.name}`}><option value="true">Activa</option><option value="false">Inactiva</option></select><button className="btn btn-secondary">Guardar</button></form>)}</div></div></details>

    <div className="section-head"><h2>Últimos gastos de eventos</h2><Link href="/eventos">Ver eventos</Link></div>
    <section className="expense-event-list">{expenses.map((expense) => <Link href={`/eventos/${expense.eventId}`} className={expense.status === "VOID" ? "expense-void" : ""} key={expense.id}><div><span className="badge">{expense.category.name}</span><strong>{expense.description}</strong><small>{expense.event.number} · Pagó {expense.paidByStaff?.name || (expense.accountId ? "Murray DJs" : "sin informar")}</small></div><strong>{formatMoney(String(expense.amount), expense.currency)}</strong></Link>)}{!expenses.length && <div className="empty-inline">Todavía no hay gastos de eventos. Se cargan desde la ficha de cada evento.</div>}</section>
  </>;
}
