import Link from "next/link";
import { Currency } from "@prisma/client";
import Decimal from "decimal.js";
import { prisma } from "@/server/db/prisma";
import { requireManagement } from "@/server/auth/authorization";
import { monthRange } from "@/lib/dates/month";
import { formatMoney } from "@/lib/money/format";

export default async function Settlements({searchParams}:{searchParams:Promise<{month?:string;currency?:string}>}){await requireManagement();const p=await searchParams,period=monthRange(p.month),currency=Object.values(Currency).includes(p.currency as Currency)?p.currency as Currency:Currency.ARS;const staff=await prisma.staff.findMany({where:{active:true},include:{eventAssignments:{where:{active:true,currency,event:{eventDate:{gte:period.start,lte:period.end}}},include:{event:true}},payments:{where:{status:"ACTIVE",currency},include:{event:true}}},orderBy:{name:"asc"}});const movements=staff.flatMap(s=>s.payments).filter(p=>p.paymentDate>=period.start&&p.paymentDate<=period.end).reduce((x,p)=>x.plus(p.amount),new Decimal(0));return <><div className="topbar"><div><div className="eyebrow">Personal</div><h1>Liquidaciones</h1><p className="muted">El trabajo se agrupa por fecha del evento; los movimientos pagados, por fecha del pago.</p></div><Link className="btn btn-secondary" href="/personal">Volver</Link></div><form method="get" className="card row filter-bar"><div className="field"><label htmlFor="settlement-month">Mes</label><input id="settlement-month" name="month" type="month" defaultValue={period.value}/></div><div className="field"><label htmlFor="settlement-currency">Moneda</label><select id="settlement-currency" name="currency" defaultValue={currency}><option>ARS</option><option>USD</option></select></div><button className="btn btn-primary">Ver liquidación</button></form><div className="card metric movement-metric"><span>Movimientos efectivamente pagados en {period.value}</span><strong>{formatMoney(movements.toFixed(2),currency)}</strong></div><div className="settlement-list">{staff.map(s=>{const due=s.eventAssignments.filter(a=>["REALIZADO","CERRADO"].includes(a.event.status)),future=s.eventAssignments.filter(a=>["CONFIRMADO","EN_PREPARACION","LISTO","EN_CURSO"].includes(a.event.status));const eventIds=new Set(due.map(a=>a.eventId));const generated=sum(due.map(a=>a.agreedAmount)),paid=sum(s.payments.filter(x=>x.eventId&&eventIds.has(x.eventId)).map(x=>x.amount)),advances=sum(s.payments.filter(x=>!x.eventId&&x.paymentDate>=period.start&&x.paymentDate<=period.end).map(x=>x.amount)),pending=generated.minus(paid).minus(advances),events=new Set(due.map(a=>a.eventId)).size;return <Link className="card settlement-row" href={`/personal/liquidaciones/${s.id}?month=${period.value}&currency=${currency}`} key={s.id}><div><strong>{s.name}</strong><small>{events} eventos realizados</small></div><Value label="Generado" value={formatMoney(generated.toFixed(2),currency)}/><Value label="Pagado" value={formatMoney(paid.toFixed(2),currency)}/><Value label="Adelantos" value={formatMoney(advances.toFixed(2),currency)}/><Value label="Pendiente" value={formatMoney(pending.toFixed(2),currency)}/>{future.length>0&&<span className="badge badge-warn">Futuro: {formatMoney(sum(future.map(x=>x.agreedAmount)).toFixed(2),currency)}</span>}</Link>})}</div></>}
const sum=(values:unknown[])=>values.reduce<Decimal>((s,v)=>s.plus(String(v)),new Decimal(0));
function Value({label,value}:{label:string;value:string}){return <div><small>{label}</small><strong>{value}</strong></div>}
