/* eslint-disable @typescript-eslint/no-explicit-any, prefer-const */
import Decimal from "decimal.js";
import Link from "next/link";
import { prisma } from "@/server/db/prisma";
import { requireManagement } from "@/server/auth/authorization";
import { monthRange } from "@/lib/dates/month";
import { calculateEventProfitability, guestRange } from "@/lib/profitability/event-profitability";
import { formatMoney } from "@/lib/money/format";
import { EmptyState, PageHeader } from "@/components/ui";

type Search={month?:string;year?:string;currency?:"ARS"|"USD";sort?:string};
export default async function ProfitabilityReport({searchParams}:{searchParams:Promise<Search>}){await requireManagement();const q=await searchParams;const today=new Date(),month=Number(q.month||today.getMonth()+1),year=Number(q.year||today.getFullYear()),currency=q.currency==="USD"?"USD":"ARS";const range=monthRange(`${year}-${String(month).padStart(2,"0")}`),from=range.start,to=new Date(Date.UTC(year,month,1));
 const events=await prisma.event.findMany({where:{eventDate:{gte:from,lt:to}},include:{client:true,eventType:true,sourceQuoteVersion:{include:{items:{include:{addOn:true}}}},staffAssignments:{where:{active:true}},expenses:{where:{status:"ACTIVE"},include:{category:true,quoteItem:{include:{addOn:true}}}}}});
 let rows=events.map(event=>({event,profit:calculateEventProfitability({version:event.sourceQuoteVersion,assignments:event.staffAssignments,expenses:event.expenses})}));const sort=q.sort||"date";rows.sort((a,b)=>sort==="result"?b.profit.byCurrency[currency].result.comparedTo(a.profit.byCurrency[currency].result):sort==="margin"?(b.profit.byCurrency[currency].marginPercentage?.comparedTo(a.profit.byCurrency[currency].marginPercentage||0)||0):sort==="sale"?b.profit.byCurrency[currency].netSale.comparedTo(a.profit.byCurrency[currency].netSale):a.event.eventDate.getTime()-b.event.eventDate.getTime());
 const closed=rows.filter(r=>r.event.financialStatus==="CLOSED"),provisional=rows.filter(r=>r.event.financialStatus!=="CLOSED"&&["REALIZADO","CERRADO"].includes(r.event.status));const totals=sumRows(closed,currency);
 const byType=group(closed,r=>r.event.eventType.name,currency),byGuests=group(closed,r=>guestRange(r.event.guestCount),currency);const categories=new Map<string,Decimal>();for(const r of closed)for(const x of r.event.expenses)if(x.currency===currency)categories.set(x.category.name,(categories.get(x.category.name)||new Decimal(0)).plus(x.amount));
 const addons=new Map<string,{count:Decimal;sale:Decimal;cost:Decimal}>();let unassigned=new Decimal(0);for(const r of closed){for(const item of r.event.sourceQuoteVersion.items){if(!item.addOn||item.currency!==currency)continue;const current=addons.get(item.addOn.name)||{count:new Decimal(0),sale:new Decimal(0),cost:new Decimal(0)};current.count=current.count.plus(item.quantity);current.sale=current.sale.plus(item.finalAmount);current.cost=current.cost.plus(r.event.expenses.filter(x=>x.quoteItemId===item.id&&x.currency===currency).reduce((s,x)=>s.plus(x.amount),new Decimal(0)));addons.set(item.addOn.name,current)}for(const x of r.event.expenses)if(x.currency===currency&&!x.quoteItemId)unassigned=unassigned.plus(x.amount)}
 return <><PageHeader eyebrow="Reportes" title="Rentabilidad" description="Solo los eventos financieramente cerrados integran los resultados definitivos."/><form className="card filters"><div className="field"><label>Mes</label><select name="month" defaultValue={month}>{Array.from({length:12},(_,i)=><option value={i+1} key={i}>{new Date(2020,i,1).toLocaleDateString("es-AR",{month:"long"})}</option>)}</select></div><div className="field"><label>Año</label><input name="year" type="number" defaultValue={year}/></div><div className="field"><label>Moneda</label><select name="currency" defaultValue={currency}><option>ARS</option><option>USD</option></select></div><div className="field"><label>Orden</label><select name="sort" defaultValue={sort}><option value="date">Fecha</option><option value="result">Resultado</option><option value="margin">Margen</option><option value="sale">Venta</option></select></div><button className="btn btn-primary">Aplicar</button></form>
 <section className="profit-grid"><Metric label="Eventos cerrados" value={String(closed.length)}/><Metric label="Venta neta" value={formatMoney(totals.sale.toFixed(2),currency)}/><Metric label="Personal" value={formatMoney(totals.staff.toFixed(2),currency)}/><Metric label="Gastos" value={formatMoney(totals.expenses.toFixed(2),currency)}/><Metric label="Resultado" value={formatMoney(totals.result.toFixed(2),currency)}/><Metric label="Margen" value={totals.sale.gt(0)?`${totals.result.div(totals.sale).times(100).toFixed(2)}%`:"—"}/></section>
 <ReportList title="Eventos cerrados" rows={closed} currency={currency}/>{provisional.length>0&&<ReportList title="Resultado provisorio · todavía abierto" rows={provisional} currency={currency}/>}<section className="grid grid-2 report-groups"><Group title="Por tipo de evento" rows={byType} currency={currency}/><Group title="Por cantidad de invitados" rows={byGuests} currency={currency}/><div className="card"><h2>Gastos por categoría</h2>{[...categories].map(([name,value])=><div className="report-row" key={name}><span>{name}</span><strong>{formatMoney(value.toFixed(2),currency)}</strong></div>)}</div><div className="card"><h2>Adicionales · costos asignados</h2>{[...addons].map(([name,v])=><div className="report-row report-row-stacked" key={name}><strong>{name}</strong><span>{v.count.toFixed(0)} vendidos · Venta {formatMoney(v.sale.toFixed(2),currency)} · Costo asignado {formatMoney(v.cost.toFixed(2),currency)} · Resultado directo {formatMoney(v.sale.minus(v.cost).toFixed(2),currency)}</span></div>)}<div className="alert">Costos no asignados a ítems: {formatMoney(unassigned.toFixed(2),currency)}. No se atribuyen automáticamente.</div></div></section></>}
function sumRows(rows:any[],currency:"ARS"|"USD"){return rows.reduce((a,r)=>({sale:a.sale.plus(r.profit.byCurrency[currency].netSale),staff:a.staff.plus(r.profit.byCurrency[currency].staffCost),expenses:a.expenses.plus(r.profit.byCurrency[currency].directExpenses),result:a.result.plus(r.profit.byCurrency[currency].result)}),{sale:new Decimal(0),staff:new Decimal(0),expenses:new Decimal(0),result:new Decimal(0)})}
function group(rows:any[],key:(r:any)=>string,currency:"ARS"|"USD"){const out=new Map<string,{count:number;sale:Decimal;result:Decimal}>();for(const r of rows){const name=key(r),v=out.get(name)||{count:0,sale:new Decimal(0),result:new Decimal(0)};v.count++;v.sale=v.sale.plus(r.profit.byCurrency[currency].netSale);v.result=v.result.plus(r.profit.byCurrency[currency].result);out.set(name,v)}return out}
function Metric({label,value}:{label:string;value:string}){return <div className="card metric"><span>{label}</span><strong>{value}</strong></div>}
function ReportList({title,rows,currency}:{title:string;rows:any[];currency:"ARS"|"USD"}){return <><div className="section-head"><h2>{title}</h2></div><div className="report-list">{rows.map(r=>{const p=r.profit.byCurrency[currency];return <Link className="card card-interactive report-event" href={`/eventos/${r.event.id}`} key={r.event.id}><div><strong>{r.event.number} · {r.event.client.name}</strong><span>{r.event.eventType.name} · {r.event.guestCount||"—"} invitados</span></div><div><span>Venta {formatMoney(p.netSale.toFixed(2),currency)}</span><span>Personal {formatMoney(p.staffCost.toFixed(2),currency)}</span><span>Gastos {formatMoney(p.directExpenses.toFixed(2),currency)}</span><strong>Resultado {formatMoney(p.result.toFixed(2),currency)} · {p.marginPercentage?.toFixed(2)||"—"}%</strong></div></Link>})}{!rows.length&&<EmptyState title="Sin eventos para este período"/>}</div></>}
function Group({title,rows,currency}:{title:string;rows:Map<string,{count:number;sale:Decimal;result:Decimal}>;currency:"ARS"|"USD"}){return <div className="card"><h2>{title}</h2>{[...rows].map(([name,v])=><div className="report-row report-row-stacked" key={name}><strong>{name}</strong><span>{v.count} eventos · Venta {formatMoney(v.sale.toFixed(2),currency)} · Resultado {formatMoney(v.result.toFixed(2),currency)} · Margen {v.sale.gt(0)?v.result.div(v.sale).times(100).toFixed(2):"—"}% · Ticket {formatMoney(v.sale.div(v.count).toFixed(2),currency)}</span></div>)}</div>}
