"use server";
import { randomUUID } from "node:crypto";
import { AssignmentType, Currency, EventStatus } from "@prisma/client";
import Decimal from "decimal.js";
import { revalidatePath } from "next/cache";
import { prisma } from "@/server/db/prisma";
import { requireOperations } from "@/server/auth/authorization";
import { audit } from "@/server/audit/audit";

export async function setEventManager(eventId:string,formData:FormData){const actor=await requireOperations(),managerStaffId=nullable(formData,"managerStaffId");await prisma.$transaction(async tx=>{const old=await tx.event.findUniqueOrThrow({where:{id:eventId}});if(managerStaffId)await tx.staff.findFirstOrThrow({where:{id:managerStaffId,active:true}});await tx.event.update({where:{id:eventId},data:{managerStaffId}});await audit(tx,{userId:actor.id,action:"UPDATE_MANAGER",entity:"Event",entityId:eventId,previousValue:{managerStaffId:old.managerStaffId},newValue:{managerStaffId},operationId:randomUUID()});});refresh(eventId);}
export async function updateEventDetails(eventId:string,formData:FormData){const actor=await requireOperations(),eventTypeId=String(formData.get("eventTypeId")||""),managerStaffId=nullable(formData,"managerStaffId");if(!eventTypeId)throw new Error("Seleccioná un tipo de evento.");await prisma.$transaction(async tx=>{const old=await tx.event.findUniqueOrThrow({where:{id:eventId}});await tx.eventType.findFirstOrThrow({where:{id:eventTypeId,active:true}});if(managerStaffId)await tx.staff.findFirstOrThrow({where:{id:managerStaffId,active:true}});const next=await tx.event.update({where:{id:eventId},data:{eventTypeId,managerStaffId}});await audit(tx,{userId:actor.id,action:"UPDATE",entity:"Event",entityId:eventId,previousValue:{eventTypeId:old.eventTypeId,managerStaffId:old.managerStaffId},newValue:{eventTypeId:next.eventTypeId,managerStaffId:next.managerStaffId},operationId:randomUUID()});});refresh(eventId);}
export async function assignStaff(eventId:string,formData:FormData){const actor=await requireOperations(),staffId=String(formData.get("staffId")),assignmentType=String(formData.get("assignmentType")) as AssignmentType,currency=String(formData.get("currency")) as Currency,amount=new Decimal(String(formData.get("agreedAmount")||0));if(!Object.values(AssignmentType).includes(assignmentType)||!Object.values(Currency).includes(currency)||amount.isNegative())throw new Error("Asignación inválida");await prisma.$transaction(async tx=>{const event=await tx.event.findUniqueOrThrow({where:{id:eventId}});assertFinancialOpen(event.financialStatus);await tx.staff.findFirstOrThrow({where:{id:staffId,active:true}});const assignment=await tx.eventStaff.upsert({where:{eventId_staffId_assignmentType:{eventId,staffId,assignmentType}},update:{agreedAmount:amount.toFixed(2),currency,notes:nullable(formData,"notes"),active:true,voidedAt:null,voidReason:null,createdById:actor.id},create:{eventId,staffId,assignmentType,agreedAmount:amount.toFixed(2),currency,notes:nullable(formData,"notes"),createdById:actor.id}});await audit(tx,{userId:actor.id,action:"ASSIGN",entity:"EventStaff",entityId:assignment.id,newValue:snapshot(assignment),operationId:randomUUID()});});refresh(eventId);}
export async function updateAssignment(id:string,formData:FormData){const actor=await requireOperations(),currency=String(formData.get("currency")) as Currency,amount=new Decimal(String(formData.get("agreedAmount")||0));if(!Object.values(Currency).includes(currency)||amount.isNegative())throw new Error("Importe inválido");let eventId="";await prisma.$transaction(async tx=>{const old=await tx.eventStaff.findUniqueOrThrow({where:{id}});eventId=old.eventId;const event=await tx.event.findUniqueOrThrow({where:{id:eventId}});assertFinancialOpen(event.financialStatus);const next=await tx.eventStaff.update({where:{id},data:{agreedAmount:amount.toFixed(2),currency,notes:nullable(formData,"notes")}});await audit(tx,{userId:actor.id,action:"UPDATE_ASSIGNMENT",entity:"EventStaff",entityId:id,previousValue:snapshot(old),newValue:snapshot(next),operationId:randomUUID()});});refresh(eventId);}
export async function removeAssignment(id:string,formData:FormData){const actor=await requireOperations();let eventId="";await prisma.$transaction(async tx=>{const old=await tx.eventStaff.findUniqueOrThrow({where:{id}});eventId=old.eventId;const event=await tx.event.findUniqueOrThrow({where:{id:eventId}});assertFinancialOpen(event.financialStatus);if(!old.active)return;const next=await tx.eventStaff.update({where:{id},data:{active:false,voidedAt:new Date(),voidReason:String(formData.get("voidReason")||"Asignación removida").trim()}});await audit(tx,{userId:actor.id,action:"REMOVE",entity:"EventStaff",entityId:id,previousValue:snapshot(old),newValue:snapshot(next),operationId:randomUUID()});});refresh(eventId);}
export async function changeEventStatus(eventId:string,formData:FormData){const actor=await requireOperations(),status=String(formData.get("status")) as EventStatus;if(!Object.values(EventStatus).includes(status))throw new Error("Estado inválido");await prisma.$transaction(async tx=>{const old=await tx.event.findUniqueOrThrow({where:{id:eventId}});await tx.event.update({where:{id:eventId},data:{status}});await audit(tx,{userId:actor.id,action:"STATUS_CHANGE",entity:"Event",entityId:eventId,previousValue:{status:old.status},newValue:{status},operationId:randomUUID()});});refresh(eventId);}
function refresh(eventId:string){revalidatePath(`/eventos/${eventId}`);revalidatePath("/staff");revalidatePath("/personal");revalidatePath("/personal/liquidaciones");revalidatePath("/dashboard");}
function nullable(formData:FormData,key:string){const value=String(formData.get(key)||"").trim();return value||null;}
function snapshot(a:{eventId:string;staffId:string;assignmentType:AssignmentType;agreedAmount:unknown;currency:Currency;notes:string|null;active:boolean}){return{eventId:a.eventId,staffId:a.staffId,assignmentType:a.assignmentType,agreedAmount:String(a.agreedAmount),currency:a.currency,notes:a.notes,active:a.active};}
function assertFinancialOpen(status:string){if(status==="CLOSED")throw new Error("Reabrí las finanzas del evento antes de modificar personal.");}
