"use server";
import { randomUUID } from "node:crypto";
import { Currency, PaymentMethod, PaymentType } from "@prisma/client";
import Decimal from "decimal.js";
import { revalidatePath } from "next/cache";
import { prisma } from "@/server/db/prisma";
import { requireManagement } from "@/server/auth/authorization";
import { audit } from "@/server/audit/audit";

export async function createStaffPayment(staffId:string,formData:FormData){const actor=await requireManagement(),eventId=nullable(formData,"eventId"),currency=String(formData.get("currency")) as Currency,paymentMethod=String(formData.get("paymentMethod")) as PaymentMethod,paymentType=String(formData.get("paymentType")) as PaymentType,amount=new Decimal(String(formData.get("amount")||0)),paymentDate=new Date(`${String(formData.get("paymentDate"))}T00:00:00.000Z`);if(!amount.isPositive()||!Object.values(Currency).includes(currency)||!Object.values(PaymentMethod).includes(paymentMethod)||!Object.values(PaymentType).includes(paymentType)||Number.isNaN(paymentDate.valueOf()))throw new Error("Pago inválido");await prisma.$transaction(async tx=>{await tx.staff.findUniqueOrThrow({where:{id:staffId}});if(eventId){const assignment=await tx.eventStaff.findFirst({where:{staffId,eventId,currency,active:true}});if(!assignment)throw new Error("No existe una obligación activa en esa moneda para este evento");}const payment=await tx.staffPayment.create({data:{staffId,eventId,amount:amount.toFixed(2),currency,paymentDate,paymentMethod,paymentType,notes:nullable(formData,"notes"),createdById:actor.id}});await audit(tx,{userId:actor.id,action:"CREATE",entity:"StaffPayment",entityId:payment.id,newValue:snapshot(payment),operationId:randomUUID()});});refresh(staffId);}
export async function voidStaffPayment(id:string,formData:FormData){const actor=await requireManagement(),reason=String(formData.get("voidReason")||"").trim();if(!reason)throw new Error("Indicá el motivo de anulación");let staffId="";await prisma.$transaction(async tx=>{const old=await tx.staffPayment.findUniqueOrThrow({where:{id}});staffId=old.staffId;if(old.status==="VOID")return;const next=await tx.staffPayment.update({where:{id},data:{status:"VOID",voidedAt:new Date(),voidedById:actor.id,voidReason:reason}});await audit(tx,{userId:actor.id,action:"VOID",entity:"StaffPayment",entityId:id,previousValue:snapshot(old),newValue:snapshot(next),operationId:randomUUID()});});refresh(staffId);}
function refresh(staffId:string){revalidatePath(`/personal/${staffId}`);revalidatePath(`/personal/liquidaciones/${staffId}`);revalidatePath("/personal/liquidaciones");revalidatePath("/personal");revalidatePath("/dashboard");}
function nullable(formData:FormData,key:string){const value=String(formData.get(key)||"").trim();return value||null;}
function snapshot(p:{staffId:string;eventId:string|null;amount:unknown;currency:Currency;paymentDate:Date;paymentMethod:PaymentMethod;paymentType:PaymentType;status:string;voidReason:string|null}){return{staffId:p.staffId,eventId:p.eventId,amount:String(p.amount),currency:p.currency,paymentDate:p.paymentDate.toISOString().slice(0,10),paymentMethod:p.paymentMethod,paymentType:p.paymentType,status:p.status,voidReason:p.voidReason};}
