"use server";
import { randomUUID } from "node:crypto";
import { ClientPaymentMethod,ClientPaymentType,Currency,Prisma,QuoteStatus,TreasuryCategory,TreasuryDirection } from "@prisma/client";
import Decimal from "decimal.js";
import { revalidatePath } from "next/cache";
import { z } from "zod";
import { prisma } from "@/server/db/prisma";
import { requireAdmin,requireManagement,requireOperations } from "@/server/auth/authorization";
import { audit } from "@/server/audit/audit";
import { createLedgerMovement,requireAccount,voidLedgerMovement } from "@/server/treasury/ledger";
import { assertSameCurrency } from "@/lib/treasury/calculations";
import { nextNumber } from "@/server/services/sequence";
import { suggestSetupTime } from "@/lib/dates/times";

const money=z.coerce.string().transform(v=>new Decimal(v)).refine(v=>v.gt(0),"El importe debe ser positivo");
const uuid=z.string().uuid(); const date=z.string().regex(/^\d{4}-\d{2}-\d{2}$/).transform(v=>new Date(`${v}T00:00:00.000Z`));
const idempotency=z.string().uuid();
const text=(data:FormData,key:string)=>String(data.get(key)||"").trim();
const nullable=(data:FormData,key:string)=>text(data,key)||null;
function refresh(){for(const path of ["/tesoreria","/tesoreria/movimientos","/tesoreria/por-cobrar","/tesoreria/por-pagar","/tesoreria/flujo","/dashboard","/personal","/gastos"])revalidatePath(path)}

export async function createOpeningBalance(data:FormData){const actor=await requireAdmin();const input=z.object({accountId:uuid,amount:money,balanceDate:date,idempotencyKey:idempotency}).parse({accountId:text(data,"accountId"),amount:text(data,"amount"),balanceDate:text(data,"balanceDate"),idempotencyKey:text(data,"idempotencyKey")});await prisma.$transaction(async tx=>{if(await tx.openingBalance.findUnique({where:{idempotencyKey:input.idempotencyKey}}))return;const account=await tx.financialAccount.findUniqueOrThrow({where:{id:input.accountId}}),id=randomUUID(),movement=await createLedgerMovement(tx,{accountId:account.id,direction:TreasuryDirection.INFLOW,category:TreasuryCategory.OPENING_BALANCE,amount:input.amount,currency:account.currency,date:input.balanceDate,description:`Saldo inicial · ${account.name}`,referenceType:"OpeningBalance",referenceId:id,createdById:actor.id,idempotencyKey:randomUUID()});const created=await tx.openingBalance.create({data:{id,accountId:account.id,amount:input.amount.toFixed(2),balanceDate:input.balanceDate,notes:nullable(data,"notes"),idempotencyKey:input.idempotencyKey,treasuryTransactionId:movement.id,createdById:actor.id}});await audit(tx,{userId:actor.id,action:"CREATE",entity:"OpeningBalance",entityId:id,newValue:{accountId:account.id,amount:String(created.amount),currency:account.currency,balanceDate:input.balanceDate.toISOString()},operationId:input.idempotencyKey});});refresh()}

export async function createClientPayment(data:FormData){const actor=await requireOperations();const input=z.object({eventId:uuid.optional(),quoteId:uuid.optional(),quoteVersionId:uuid.optional(),accountId:uuid.optional(),amount:money,paymentDate:date,paymentMethod:z.nativeEnum(ClientPaymentMethod),paymentType:z.nativeEnum(ClientPaymentType),idempotencyKey:idempotency,confirmQuote:z.boolean()}).parse({eventId:nullable(data,"eventId")||undefined,quoteId:nullable(data,"quoteId")||undefined,quoteVersionId:nullable(data,"quoteVersionId")||undefined,accountId:nullable(data,"accountId")||undefined,amount:text(data,"amount"),paymentDate:text(data,"paymentDate"),paymentMethod:text(data,"paymentMethod"),paymentType:text(data,"paymentType"),idempotencyKey:text(data,"idempotencyKey"),confirmQuote:data.get("confirmQuote")==="true"});if(!input.eventId&&!input.quoteId)throw new Error("Asociá el cobro a un evento o presupuesto");await prisma.$transaction(async tx=>{if(await tx.clientPayment.findUnique({where:{idempotencyKey:input.idempotencyKey}}))return;let event=input.eventId?await tx.event.findUniqueOrThrow({where:{id:input.eventId}}):null;const quoteId=input.quoteId||event?.sourceQuoteId;if(!quoteId)throw new Error("Presupuesto inválido");const quote=await tx.quote.findUniqueOrThrow({where:{id:quoteId}});if(!event)event=await tx.event.findUnique({where:{sourceQuoteId:quote.id}});const versionId=input.quoteVersionId||event?.sourceQuoteVersionId||quote.confirmedVersionId;const version=versionId?await tx.quoteVersion.findFirst({where:{id:versionId,quoteId:quote.id}}):null;if(!version)throw new Error("Seleccioná una versión comercial");if(input.accountId)await requireAccount(tx,input.accountId,version.currency);if(input.confirmQuote&&!event){const number=await nextNumber(tx,"EVENT",quote.eventDate);event=await tx.event.create({data:{number,clientId:quote.clientId,eventTypeId:quote.eventTypeId,sourceQuoteId:quote.id,sourceQuoteVersionId:version.id,eventDate:quote.eventDate,startTime:quote.startTime,endTime:quote.endTime,setupTime:suggestSetupTime(quote.startTime),guestCount:quote.guestCount,venue:quote.venue,address:quote.address,locality:quote.locality,googleMapsUrl:quote.googleMapsUrl,notes:quote.notes}});await tx.quote.update({where:{id:quote.id},data:{status:QuoteStatus.CONFIRMADO,confirmedVersionId:version.id}});await audit(tx,{userId:actor.id,action:"CONFIRM_AND_CREATE_EVENT",entity:"Quote",entityId:quote.id,newValue:{versionId:version.id,eventId:event.id,eventNumber:number},operationId:input.idempotencyKey});}
 const id=randomUUID();const movement=input.accountId?await createLedgerMovement(tx,{accountId:input.accountId,direction:TreasuryDirection.INFLOW,category:TreasuryCategory.CLIENT_PAYMENT,amount:input.amount,currency:version.currency,date:input.paymentDate,description:`Cobro ${input.paymentType} · ${quote.number}`,referenceType:"ClientPayment",referenceId:id,createdById:actor.id}):null;const created=await tx.clientPayment.create({data:{id,clientId:quote.clientId,eventId:event?.id||null,quoteId:quote.id,quoteVersionId:version.id,accountId:input.accountId,amount:input.amount.toFixed(2),currency:version.currency,paymentDate:input.paymentDate,paymentMethod:input.paymentMethod,paymentType:input.paymentType,notes:nullable(data,"notes"),receivedViaPartner:data.get("receivedViaPartner")==="true",partnerName:nullable(data,"partnerName"),idempotencyKey:input.idempotencyKey,treasuryTransactionId:movement?.id,createdById:actor.id}});await audit(tx,{userId:actor.id,action:"CREATE",entity:"ClientPayment",entityId:id,newValue:{quoteId:quote.id,eventId:event?.id||null,amount:String(created.amount),currency:created.currency,accountId:created.accountId,paymentType:created.paymentType},operationId:input.idempotencyKey});},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable});refresh();if(input.eventId)revalidatePath(`/eventos/${input.eventId}`);if(input.quoteId)revalidatePath(`/presupuestos/${input.quoteId}`)}

export async function voidClientPayment(id:string,data:FormData){const actor=await requireManagement(),reason=text(data,"voidReason");if(!reason)throw new Error("Indicá el motivo de anulación");await prisma.$transaction(async tx=>{const old=await tx.clientPayment.findUniqueOrThrow({where:{id}});if(old.status==="VOID")return;const next=await tx.clientPayment.update({where:{id},data:{status:"VOID",voidedAt:new Date(),voidedById:actor.id,voidReason:reason}});if(old.treasuryTransactionId)await voidLedgerMovement(tx,old.treasuryTransactionId,actor.id,reason);await audit(tx,{userId:actor.id,action:"VOID",entity:"ClientPayment",entityId:id,previousValue:{status:old.status,amount:String(old.amount)},newValue:{status:next.status,reason},operationId:randomUUID()});});refresh()}

export async function createAccountTransfer(data:FormData){const actor=await requireManagement();const input=z.object({fromAccountId:uuid,toAccountId:uuid,amount:money,transferDate:date,idempotencyKey:idempotency}).parse({fromAccountId:text(data,"fromAccountId"),toAccountId:text(data,"toAccountId"),amount:text(data,"amount"),transferDate:text(data,"transferDate"),idempotencyKey:text(data,"idempotencyKey")});if(input.fromAccountId===input.toAccountId)throw new Error("Elegí cuentas diferentes");await prisma.$transaction(async tx=>{if(await tx.accountTransfer.findUnique({where:{idempotencyKey:input.idempotencyKey}}))return;const [from,to]=await Promise.all([tx.financialAccount.findUniqueOrThrow({where:{id:input.fromAccountId}}),tx.financialAccount.findUniqueOrThrow({where:{id:input.toAccountId}})]);assertSameCurrency(from.currency,to.currency);const id=randomUUID(),description=nullable(data,"description")||`Transferencia ${from.name} → ${to.name}`;const out=await createLedgerMovement(tx,{accountId:from.id,direction:"OUTFLOW",category:"TRANSFER",amount:input.amount,currency:from.currency,date:input.transferDate,description,referenceType:"AccountTransfer",referenceId:id,createdById:actor.id});const incoming=await createLedgerMovement(tx,{accountId:to.id,direction:"INFLOW",category:"TRANSFER",amount:input.amount,currency:to.currency,date:input.transferDate,description,referenceType:"AccountTransfer",referenceId:id,createdById:actor.id});await tx.accountTransfer.create({data:{id,fromAccountId:from.id,toAccountId:to.id,amount:input.amount.toFixed(2),currency:from.currency,transferDate:input.transferDate,description,idempotencyKey:input.idempotencyKey,outTransactionId:out.id,inTransactionId:incoming.id,createdById:actor.id}});await audit(tx,{userId:actor.id,action:"CREATE",entity:"AccountTransfer",entityId:id,newValue:{from:from.id,to:to.id,amount:input.amount.toFixed(2),currency:from.currency},operationId:input.idempotencyKey});},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable});refresh()}

export async function createAdjustment(data:FormData){const actor=await requireAdmin();const input=z.object({accountId:uuid,amount:money,direction:z.nativeEnum(TreasuryDirection),transactionDate:date,idempotencyKey:idempotency}).parse({accountId:text(data,"accountId"),amount:text(data,"amount"),direction:text(data,"direction"),transactionDate:text(data,"transactionDate"),idempotencyKey:text(data,"idempotencyKey")});const reason=text(data,"reason");if(!reason)throw new Error("El ajuste requiere motivo");await prisma.$transaction(async tx=>{if(await tx.treasuryTransaction.findUnique({where:{idempotencyKey:input.idempotencyKey}}))return;const account=await tx.financialAccount.findUniqueOrThrow({where:{id:input.accountId}}),movement=await createLedgerMovement(tx,{accountId:account.id,direction:input.direction,category:"ADJUSTMENT",amount:input.amount,currency:account.currency,date:input.transactionDate,description:`Ajuste · ${reason}`,referenceType:"Adjustment",referenceId:input.idempotencyKey,createdById:actor.id,idempotencyKey:input.idempotencyKey});await audit(tx,{userId:actor.id,action:"CREATE",entity:"Adjustment",entityId:movement.id,newValue:{accountId:account.id,direction:input.direction,amount:input.amount.toFixed(2),reason},operationId:input.idempotencyKey});});refresh()}

export async function createOwnerMovement(kind:"WITHDRAWAL"|"CONTRIBUTION",data:FormData){const actor=await requireAdmin();const input=z.object({accountId:uuid,amount:money,movementDate:date,idempotencyKey:idempotency}).parse({accountId:text(data,"accountId"),amount:text(data,"amount"),movementDate:text(data,"movementDate"),idempotencyKey:text(data,"idempotencyKey")});await prisma.$transaction(async tx=>{const account=await tx.financialAccount.findUniqueOrThrow({where:{id:input.accountId}}),id=randomUUID(),entity=kind==="WITHDRAWAL"?"OwnerWithdrawal":"OwnerContribution";if(kind==="WITHDRAWAL"&&await tx.ownerWithdrawal.findUnique({where:{idempotencyKey:input.idempotencyKey}}))return;if(kind==="CONTRIBUTION"&&await tx.ownerContribution.findUnique({where:{idempotencyKey:input.idempotencyKey}}))return;const movement=await createLedgerMovement(tx,{accountId:account.id,direction:kind==="WITHDRAWAL"?"OUTFLOW":"INFLOW",category:kind==="WITHDRAWAL"?"OWNER_WITHDRAWAL":"OWNER_CONTRIBUTION",amount:input.amount,currency:account.currency,date:input.movementDate,description:`${kind==="WITHDRAWAL"?"Retiro":"Aporte"} · ${nullable(data,"notes")||"Sin nota"}`,referenceType:entity,referenceId:id,createdById:actor.id});if(kind==="WITHDRAWAL")await tx.ownerWithdrawal.create({data:{id,staffId:nullable(data,"staffId"),accountId:account.id,amount:input.amount.toFixed(2),currency:account.currency,withdrawalDate:input.movementDate,notes:nullable(data,"notes"),idempotencyKey:input.idempotencyKey,treasuryTransactionId:movement.id,createdById:actor.id}});else await tx.ownerContribution.create({data:{id,accountId:account.id,amount:input.amount.toFixed(2),currency:account.currency,contributionDate:input.movementDate,notes:nullable(data,"notes"),idempotencyKey:input.idempotencyKey,treasuryTransactionId:movement.id,createdById:actor.id}});await audit(tx,{userId:actor.id,action:"CREATE",entity,entityId:id,newValue:{accountId:account.id,amount:input.amount.toFixed(2),currency:account.currency},operationId:input.idempotencyKey});});refresh()}

export async function payReimbursement(id:string,data:FormData){const actor=await requireManagement();const accountId=nullable(data,"accountId"),paidAt=date.parse(text(data,"paidAt")),key=idempotency.parse(text(data,"idempotencyKey"));await prisma.$transaction(async tx=>{const old=await tx.staffReimbursement.findUniqueOrThrow({where:{id},include:{staff:true}});if(old.status==="PAID")return;if(old.status!=="PENDING")throw new Error("El reintegro no está pendiente");if(accountId)await requireAccount(tx,accountId,old.currency);const movement=accountId?await createLedgerMovement(tx,{accountId,direction:"OUTFLOW",category:"REIMBURSEMENT",amount:old.amount,currency:old.currency,date:paidAt,description:`Reintegro · ${old.staff.name}`,referenceType:"StaffReimbursement",referenceId:id,createdById:actor.id,idempotencyKey:key}):null;const next=await tx.staffReimbursement.update({where:{id},data:{status:"PAID",paidAt,paymentAccountId:accountId,treasuryTransactionId:movement?.id||null,paidById:actor.id}});await audit(tx,{userId:actor.id,action:"PAY",entity:"StaffReimbursement",entityId:id,previousValue:{status:old.status},newValue:{status:next.status,accountId,amount:String(next.amount)},operationId:key});});refresh()}

export async function updateFinancialSetting(currency:Currency,data:FormData){const actor=await requireAdmin(),reserve=new Decimal(text(data,"minimumCashReserve")||0),tracking=nullable(data,"financialTrackingStartDate");if(reserve.lt(0))throw new Error("Reserva inválida");await prisma.$transaction(async tx=>{const previous=await tx.financialSetting.findUnique({where:{currency}});const next=await tx.financialSetting.upsert({where:{currency},update:{minimumCashReserve:reserve.toFixed(2),financialTrackingStartDate:tracking?new Date(`${tracking}T00:00:00.000Z`):null,updatedById:actor.id},create:{currency,minimumCashReserve:reserve.toFixed(2),financialTrackingStartDate:tracking?new Date(`${tracking}T00:00:00.000Z`):null,updatedById:actor.id}});await audit(tx,{userId:actor.id,action:"UPDATE",entity:"FinancialSetting",entityId:next.id,previousValue:previous?{reserve:String(previous.minimumCashReserve),date:previous.financialTrackingStartDate?.toISOString()||null}:undefined,newValue:{reserve:String(next.minimumCashReserve),date:next.financialTrackingStartDate?.toISOString()||null},operationId:randomUUID()});});refresh()}

export async function createFinancialAccount(data:FormData){const actor=await requireAdmin(),name=text(data,"name"),currency=z.nativeEnum(Currency).parse(text(data,"currency")),type=text(data,"type") as "CASH"|"BANK"|"MERCADO_PAGO"|"THIRD_PARTY"|"OTHER";if(!name)throw new Error("Nombre requerido");const created=await prisma.$transaction(async tx=>{const account=await tx.financialAccount.create({data:{name,type,currency,includeInAvailableCash:data.get("includeInAvailableCash")==="true",notes:nullable(data,"notes")}});await audit(tx,{userId:actor.id,action:"CREATE",entity:"FinancialAccount",entityId:account.id,newValue:{name,type,currency,includeInAvailableCash:account.includeInAvailableCash},operationId:randomUUID()});return account});revalidatePath(`/tesoreria/cuentas/${created.id}`);refresh()}

export async function voidAccountTransfer(id:string,data:FormData){const actor=await requireManagement(),reason=text(data,"voidReason");if(!reason)throw new Error("Indicá el motivo");await prisma.$transaction(async tx=>{const old=await tx.accountTransfer.findUniqueOrThrow({where:{id}});if(old.status==="VOID")return;await Promise.all([voidLedgerMovement(tx,old.outTransactionId,actor.id,reason),voidLedgerMovement(tx,old.inTransactionId,actor.id,reason)]);await tx.accountTransfer.update({where:{id},data:{status:"VOID",voidedAt:new Date(),voidedById:actor.id,voidReason:reason}});await audit(tx,{userId:actor.id,action:"VOID",entity:"AccountTransfer",entityId:id,previousValue:{status:old.status},newValue:{status:"VOID",reason},operationId:randomUUID()});});refresh()}

export async function voidOwnerMovement(kind:"WITHDRAWAL"|"CONTRIBUTION",id:string,data:FormData){const actor=await requireAdmin(),reason=text(data,"voidReason");if(!reason)throw new Error("Indicá el motivo");await prisma.$transaction(async tx=>{const old=kind==="WITHDRAWAL"?await tx.ownerWithdrawal.findUniqueOrThrow({where:{id}}):await tx.ownerContribution.findUniqueOrThrow({where:{id}});if(old.status==="VOID")return;await voidLedgerMovement(tx,old.treasuryTransactionId,actor.id,reason);if(kind==="WITHDRAWAL")await tx.ownerWithdrawal.update({where:{id},data:{status:"VOID",voidedAt:new Date(),voidedById:actor.id,voidReason:reason}});else await tx.ownerContribution.update({where:{id},data:{status:"VOID",voidedAt:new Date(),voidedById:actor.id,voidReason:reason}});await audit(tx,{userId:actor.id,action:"VOID",entity:kind==="WITHDRAWAL"?"OwnerWithdrawal":"OwnerContribution",entityId:id,previousValue:{status:old.status},newValue:{status:"VOID",reason},operationId:randomUUID()});});refresh()}

export async function updateFinancialAccount(id:string,data:FormData){const actor=await requireAdmin();await prisma.$transaction(async tx=>{const old=await tx.financialAccount.findUniqueOrThrow({where:{id}}),active=text(data,"active")!=="false",includeInAvailableCash=data.get("includeInAvailableCash")==="true",name=text(data,"name")||old.name;const next=await tx.financialAccount.update({where:{id},data:{name,active,includeInAvailableCash,notes:nullable(data,"notes")}});await audit(tx,{userId:actor.id,action:active?"UPDATE":"DEACTIVATE",entity:"FinancialAccount",entityId:id,previousValue:{name:old.name,active:old.active,includeInAvailableCash:old.includeInAvailableCash},newValue:{name:next.name,active:next.active,includeInAvailableCash:next.includeInAvailableCash},operationId:randomUUID()});});refresh();revalidatePath(`/tesoreria/cuentas/${id}`)}

export async function updatePaymentDueDate(quoteId:string,data:FormData){const actor=await requireOperations(),value=nullable(data,"paymentDueDate"),due=value?new Date(`${value}T00:00:00.000Z`):null;await prisma.$transaction(async tx=>{const old=await tx.quote.findUniqueOrThrow({where:{id:quoteId}}),next=await tx.quote.update({where:{id:quoteId},data:{paymentDueDate:due}});await audit(tx,{userId:actor.id,action:"UPDATE_PAYMENT_DUE_DATE",entity:"Quote",entityId:quoteId,previousValue:{paymentDueDate:old.paymentDueDate?.toISOString()||null},newValue:{paymentDueDate:next.paymentDueDate?.toISOString()||null},operationId:randomUUID()});});revalidatePath(`/presupuestos/${quoteId}`);refresh()}
